### ISSUE TITLE
indexer 2.12.0 Release

### ISSUE THREAD

**Issue by onetechnical** [algorand/indexer#1015]
Data directory support and golang 1.17 upgrade

No special from scratch testing required - upgrade and verify are sufficient.

**Comment by onetechnical** [comment]
Review this PR for relevant changes required:

https://github.com/algorand/indexer/pull/1012/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by algobarb** [comment]
Released on Wed Jun 22: https://forum.algorand.org/t/algorand-indexer-update-2-12-0-new-required-parameter/7254
