### ISSUE TITLE
Cannot run Indexer

### ISSUE THREAD

**Issue by KorayBarkin** [algorand/indexer#1051]
Hello everyone, I did follow the docs but could not figure it out how to run Indexer.
Guide: https://developer.algorand.org/docs/run-a-node/setup/indexer/

I'd like to run indexer to subscribe blocks for following deposits. 

Tried this one:
`./algorand-indexer daemon -P “host=172.32.30.79 port=1923 user=algorand password=pass dbname=algodb sslmode=disable" --algod-net="http://172.32.30.79:4160" --algod-token="/home/ubuntu/node/data/algod.token” --data-dir="/home/ubuntu/indexer/algorand-indexer_linux_amd64_2.12.0/datadir"`

Error:
`{"error":"connecting to postgres: failed to connect to `host=/tmp user=ubuntu database=`: dial error (dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory)","level":"error","msg":"could not init db, connecting to postgres: failed to connect to `host=/tmp user=ubuntu database=`: dial error (dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory)","time":"2022-06-23T12:10:22Z"}`

What parameters should I pass to run Indexer? Any help appreciated, thanks in advance!

**Comment by winder** [comment]
That error message is from the database driver and means it was unable to connect to your database.

Depending on your configuration your next step might be using `psql` to make sure your database is healthy.

**Comment by KorayBarkin** [comment]
Do I need to create and run postgredb or is it in the indexer instance? I didn't install and create any db. The documentation did not mention such thing.

**Comment by winder** [comment]
You need to run postgres yourself and provide a connection string.

**Comment by winder** [comment]
Could you suggest a place in the documentation where you wou
