### ISSUE TITLE
Indexer Local Ledger Release Testing

### ISSUE THREAD

**Issue by winder** [algorand/indexer#1088]
### Subject of the issue

Due to the scope of changes in the data processing path, a full set of Indexer tests are required for this release.

* Testing for all production networks mainnet, testnet, betanet:
    * New deployment starting from an empty database.
        * Data validator run after the new deployment has caught up.
    * Upgrade test from  previous release 2.11.1
        * Data validator run after the new deployment has caught up.
    * Lamprey to verify any errors reported by data validator.
* Import performance test (in the past @winder runs this)

Additional details are available here:
https://algorand.atlassian.net/wiki/spaces/DEVOPS/pages/2360672259/2022-03-08+Indexer+Release+Testing+Discussion

**Comment by algobarb** [comment]
We did the upgrade test and the full catch up test for betanet, testnet, and mainnet.
We found a bug in the full testnet catchup.
Will resolved the bug and it was able to successfully catch up.

We ran indexer validation and did not see any outstanding errors. The files were shared on #indexer slack channel.
Will ran the import performance test.
