### ISSUE TITLE
add query checks for big numbers

### ISSUE THREAD

**Issue by winder** [algorand/indexer#1116]
### Subject of the issue

Several table fields use postgres `bigint` types to represent `uint64` data. Unfortunately postgres uses a signed 8 bytes integer to represent `bigint`. This means that there are weird error messages when you try to do things like query for block `18446744073709551613`.

We should add checks that return an error to the user when the queried round is > max_int.

# Acceptance Criteria
* Add big number checks and return an error message.
* New tests to make sure this check is work properly.

**Comment by shiqizng** [comment]
I think we can change bigint to numeric, https://www.postgresql.org/docs/current/datatype-numeric.html

**Comment by shiqizng** [comment]
Changing the acceptance criteria because updating the column type on an existing table requires more effort than expected.
