### ISSUE TITLE
Replace LedgerForEvaluator with the now-public StartEvaluator.

### ISSUE THREAD

**Issue by winder** [algorand/indexer#1128]
### Subject of the issue

If https://github.com/algorand/go-algorand/pull/4272 is merged, we will be able to replace `processor/blockprocessor/eval` with a direct call to `StartEvaluator` / `EvaluatorOptions`.

This would allow us to simplify the block processor quite a bit, and allow go-algorand to deprecate/remove the `LedgerForEvaluator` functionality.

**Comment by gmalouf** [comment]
Since the Conduit split, this is no longer a wish list item/relevant.
