### ISSUE TITLE
Design Non-Archival Mode

### ISSUE THREAD

**Issue by winder** [algorand/indexer#1160]
# Acceptance criteria

Figure out how a non-archival mode can fit in with the current Indexer, and Conduit.

It may be two feature:
1) initializing from a catchpoint
2) pruning data based on some TTL

**Comment by shiqizng** [comment]
non-archive mode [design doc](https://docs.google.com/document/d/1SDZkdE-3FdfGSXttewtXDt7PigGwPML24fLCNYREnGM/edit?usp=sharing)
