### ISSUE TITLE
SPIKE: Coordinate w/ HyperFlow on build/test/release cycle for Conduit

### ISSUE THREAD

**Issue by Eric-Warehime** [algorand/indexer#1195]
* Figure out build story--using mule or go-releaser (via removing cgo)?
* Versioning/tagging for conduit/indexer
* Performance/regression testing for conduit
* Release cycle--we now have indexer/conduit in the same repo

Acceptance Criteria:
* Create follow up tasks

**Comment by chaihoang** [comment]
https://github.com/algorand/indexer/issues/1216
