### ISSUE TITLE
SPIKE: Coordinate w/ DevRel on docs/developer portal

### ISSUE THREAD

**Issue by Eric-Warehime** [algorand/indexer#1196]
* Figure out the documentation story--do we want a combination of docs in READMEs/repo files or all in the dev portal
* Do we need new getting started examples or sample configurations
* What is the process around adding new plugins?
 * Should we add a new entry in the dev portal showing usage
 * How do we easily expose config arguments for plugins

Acceptance Criteria:
* Create follow up tasks

**Comment by chaihoang** [comment]
#1266
