### ISSUE TITLE
Include conduit preview binary with Indexer release

### ISSUE THREAD

**Issue by winder** [algorand/indexer#1216]
We have a new `make conduit` target to build the `conduit binary`, this should be included in the release process.

There should be a new set of artifacts which start with `conduit_`.

## Acceptance Criteria

- Conduit build is added to Indexer release pipeline
- Binaries uploaded with rest of indexer binaries

# Functional Information
- Is conduit building already? In Conduit branch, type make conduit to build it
- Platforms to support -- Linux / Mac (skip Debian package, all other platforms should be included)
- This should augment our currently indexer release pipeline. Basically, make it part of the indexer release pipeline
- Conduit is generalizing the indexer writer, should allow you to filter your data
- Stretch -- include Debian build packages
- Talk to will about integration tests (these should be done by lamprey, does this already exist? abundance of caution) 

## Miscellaneous
Any testing required?

One potential test:

- Use conduit to populate postgres.
- Start an indexer reader pointed at conduit postgres
- Run validator against this indexer reader to validate correctness

**Comment by onetechnical** [comment]
Jack, follow up with Will on testing requirements to ensure we feel comfortable with release binaries.

**Comment by algojack** [comment]
they included e2e and unit tests in the indexer to test the new binary too. So the new binary is covered with tests just like indexer.
Also there was a demo:
* this is an in-house made tool
* it connects to algod node
* has a conduit.yml config file
* runs in the background as a script
* in config it has where to connect to algod node, where to export (for example slack), and what to filter (for example only transactions to a specific wallet id)

**Comment by jsgranados** [comment]
Closing ticket. Binaries for conduit were built and stored in our releases bucket. Any further work will be done through a different ticket
