### ISSUE TITLE
Assets by (long) name query is slow

### ISSUE THREAD

**Issue by devendr4** [algorand/indexer#1236]
### Subject of the issue

Whenever I query all assets by a longish name (6 characters or more) the query takes about 10 to 20 seconds, sometimes timing out.

Query I'm using
`/v2/assets?limit=10&name=ible%20city
`
I'm running a full archival node and it's about 3.1TB of size currently, so, would this be the expected behavior for this type of node?

### Steps to reproduce

1. Query the indexer using `/v2/assets?limit=10&name=ible%20city
`
My indexer is currently private and protected but I could open it up if further testing is required.

### Expected behaviour

I've been testing AlgoExplorer's public indexer and it takes usually less than 2 seconds to do the same query, not sure if that would be a fair comparison. 

AlgoExplorer's time 
![image](https://user-images.githubusercontent.com/39252256/191657786-125e0641-d501-4ef9-9a66-b0e7bfa1229c.png)

### Actual behaviour 

My indexer's time 
![image](https://user-images.githubusercontent.com/39252256/191657956-d6aab371-7937-475d-9cda-ce802b4bce90.png)

I'd appreciate any guidance on this or clarification if this is the expected behavior for the type of node I'm running.

**Comment by winder** [comment]
This filter is disabled by default because there is no Index to support it. You can read about how to go about optimizing specific queries here:

https://github.com/algorand/indexer/blob/develop/docs/PostgresqlIndexes.md
