### ISSUE TITLE
Give txn_participation / txn tables more context about transactions

### ISSUE THREAD

**Issue by Blackglade** [algorand/indexer#1252]
## Problem

The `txn_participation` table becomes useless when trying to query info about an address as it relates to a specific asset. 

for example, doing something like this:

```
SELECT * FROM txn_participation 
LEFT JOIN txn on txn_participation.round = txn.round AND txn_participation.intra = txn.intra 
WHERE addr = <ADDRESS> AND asset = <Random ASA/APP> LIMIT 1000;

```
will take forever on certain addresses due to the sheer number of txns they generate.

On the flipside, the `txn` table gives me no context on the sender and receiver of a txn which itself is hidden behind a deeply nested json blob making indexing it impossible. The sender / receiver is a core part of every txn and should be surfaced as such.

## Solution

Add context to the `txn_participation` table regarding an asset or even better add context to the `txn` table regarding the sender and receiver of a txn instead of nestling it within a json blob.

## Urgency

No urgency, but I think having the ability for a user to ask about the txns involved with a specific app/asset as it relates to some sender or receiver (whether that be another address, app, or asset) and have it not be an intensive query to run is important.

**Comment by winder** [comment]
This table is specifically for matching accounts to transactions. It sounds like you might need a custom lookup table or index for the questions your trying to answer.
