### ISSUE TITLE
inner transaction rows have txn json from the root transaction

### ISSUE THREAD

**Issue by richalgo** [algorand/indexer#1292]
### inner transaction rows have txn json from the root transaction

In the indexer db I'm finding some rows for inner transactions (`txid == null`) where the `txn` column contains the json of the root transaction rather than the actual inner transaction.  In these cases the `txn` column for the root transaction looks correct, and it contains all the inner transactions in the `dt.itx` array.  However for each inner transaction row, the `txn` json object is that of the root transaction without the `gh` or `gen` fields

All other columns, including `typeenum`, appear to be correct for the inner transaction rows.  So one way to find these occurrences is to search for rows where `typeenum != txn.txn.type`.

I found 561,824 rows all between rounds 17400222 and 19595780 (11/13/21 - 3/4/22)

### Your environment

Using the internal indexer deployment 

### Steps to reproduce

Run this query to see an example

```
select * from txn where round=19142431 and intra in (53, 54);
```

### Expected behaviour

The inner transaction (`intra == 54`) should have `txn` object:

```
"txn": {
          "fv": 19142355,
          "lv": 19143355,
          "amt": 3562260,
          "rcv": "Ab23Amsf94tiYQNnkHghgi0la7kE65CXgz+JqBgqBq4=",
          "snd": "mR9UDVLuo+jBKhcYhtQQW2n/F9JtY6i8PE0hHBr05gQ=",
          "type": "pay"
        }
``` 

### Actual behaviour

instead it has:

```
"txn": {
    "fv": 19142355,
    "lv": 19143355,
    "fee": 2000,
    "grp": "085LwsArq8dwH0n/TqtGVX5aSSXP/pmCjdU3/mbN404=",
    "snd": "Ab23Amsf94tiYQNnkHghgi0la7kE65CXgz+JqBgqBq4=",
    "apaa": [
      "Y2xhaW0=",
      "AAABIw=="
    ],
    "apid": 594483247,
    "type": "appl"
  }
```

# Acceptance Criteria

1. Verify the issue and when it was fixed.
2. Create a migration to repair the data.

**Comment by richalgo** [comment]
This change included in the 2.9 release may have fixed the root cause:
https://github.com/algorand/indexer/commit/2d47aa25519afb0a33bdfec83d27911325c609f2#diff-d58675ce65f5a353685d874ec6b2409872307a37816077b79d2b4894272be347

**Comment by richalgo** [comment]
this query will find the rows in the indexer db but it takes a long time to run. I can share the data directly if needed

```
select * from (
    select round, intra, 
        case when typeenum = 1 then 'pay' 
            when typeenum = 2 then 'keyreg' 
            when typeenum = 3 then 'acfg' 
            when typeenum = 4 then 'axfer' 
            when typeenum = 5 then 'afrz' 
            when typeenum = 6 then 'appl' 
            when typeenum = 7 then 'stpf' 
            else '?'
        end as type_col, 
            txn -> 'txn' ->> 'type' as type_json  
    from txn where round >= 17400222 and round <=19595780
) x where type_col != type_json
```

**Comment by winder** [comment]
This was fixed
