### ISSUE TITLE
Config file doesn't allow quotes

### ISSUE THREAD

**Issue by winder** [algorand/indexer#131]
The postgres string has spaces in it, so it makes sense that the value would be quoted. But the current config file parser assumes a strict "key:value" per line.

Since we were going for YAML-ish, we should consider supporting quoted values

**Comment by brianolson** [comment]
Aside from stripping leading and trailing space, the whole string should pass through just fine?

**Comment by winder** [comment]
The suggestion here is to also strip quotes.

Someone shared a config file which wasn't working, the problem was that the value was wrapped in single quotes. After removing the quotes it worked fine.
