### ISSUE TITLE
Transaction State Delta Response Object Inconsistent

### ISSUE THREAD

**Issue by Blackglade** [algorand/indexer#1313]
### Subject of the issue

So the response regarding the state delta object (for both local/global) seems to be inconsistent depending on whether a byte is changed vs a uint. Take a look at this response: 

https://algoindexer.algoexplorerapi.io/v2/transactions?txid=LJD4CPWPLE2OMZACWFXJUOMNE6MBP4HZ6BB7AURVINS6PFAQ4WUA

local-state-delta -> when some bytes are being changed, the value object still includes the `uint` key, but just sets it to 0
vs when some uint is changed, the value object includes only `uint` key. It should be that only the `byte` key is included, right?

Not sure if this is intentional or just something that has gone unnoticed.

**Comment by winder** [comment]
Are you referring to this? It does look a little out of place.

![image.png](https://images.zenhubusercontent.com/5ceff6141df6f337c834a856/6e59ea8a-d374-428f-be83-13432a0f490b)

**Comment by Blackglade** [comment]
Sorry @winder, got lost in my inbox. Yes I was referring to that!
