### ISSUE TITLE
Bad Defaults in KeyReg Transaction Response on /v2/transactions/{txid}

### ISSUE THREAD

**Issue by Blackglade** [algorand/indexer#1319]
### Subject of the issue

When hitting the `/v2/transactions/{txid}` regarding a keyreg transactions, if there is no key reg information found on the txn json blob (`txn` column in the indexer db), it returns a response like this:

```
...
        "id": "JIFB7QOQGUQWQIEARUEALJLIIDAFJ5XVEUG6EVCX2ETHJONUOF6Q",
        "intra-round-offset": 67,
        "keyreg-transaction": {
            "non-participation": false,
            "vote-first-valid": 0,
            "vote-key-dilution": 0,
            "vote-last-valid": 0
        },
...
```

These feel like a bad set of defaults given the fact that none of the following keys exist in the `txn` json blob:

- `nonpart` => Non Particpation
- `votefst` => Vote First
- `votekd` => Key Dilution
- `votelst` => Vote Last

Defaulting to 0/false as a value when no values are actually found seems like a bad design decision. Why not just include an empty object instead of these invalid values. A user might incorrectly interpret these as valid values.

This is opposed to what a normal response with valid values would look like:
```
        "id": "X2YEXYGF4N5AMHZVFH4GI3FHIMIQL6GWAWS6P3FYFNDBY2IHTHBA",
        "intra-round-offset": 11,
        "keyreg-transaction": {
            "non-participation": false,
            "selection-participation-key": "vtpI65qqT5e7awnBqTIBGFJ1u0R7GtvFXOySFU9f64o=",
            "state-proof-key": "8P6S6FW8EGFK1sLN+vKBWZGN7AhhMs1K7XrOf3JPXfwwytBLTOBMyB5szMPO64JnlxiR/zY2MmLXAT4WEwhBpQ==",
            "vote-first-valid": 24671943,
            "vote-key-dilution": 123,
            "vote-last-valid": 24686943,
            "vote-participation-key": "jQjTAL4M/Eo/VMuIQkgPzQabniCybVVSsNnYEKDbhMY="
        },
```

**Comment by winder** [comment]
This was a decision we made early on. Sometimes Indexer will return the empty values even though the canonical representation would have removed them.
