### ISSUE TITLE
Include Decimals in ASA Transfer Transaction.

### ISSUE THREAD

**Issue by Blackglade** [algorand/indexer#1322]
## Problem

Decimals for a specific ASA aren't included in the ASA Transfer Transaction response via `/v2/transactions/{txid}`. 
See the spec here: https://developer.algorand.org/docs/rest-apis/indexer/#transactionassettransfer

This doesn't make sense as a user pinging some x ASA Transfer Tx will not know how to interpret the amount values.

## Urgency

LOW

**Comment by winder** [comment]
This is the same behavior as account balances being returned as microalgos instead of algos. If an application needs to display the units/decimals in a UI they should look up the asset metadata.
