### ISSUE TITLE
Indexer not returning UTC time for transactions

### ISSUE THREAD

**Issue by pbennett** [algorand/indexer#134]
The new indexer isn't properly returning UTC for block times - specifically inside transactions.

The 'timestamp' from the block header is correct and returned as UTC.

The 'round-time' within each transaction (particularly when querying just transactions, since it's all you get) is supposed to be returned as UTC, but is actually local time.  

In my case, that puts it 4 hours behind.

Grabbing a recent block as an example (7399860):

```
goal ledger block 7399860 --b32|grep ts
    "ts": 1592757181,
curl -s 'localhost:8980/v2/blocks/7399860?pretty'|grep timestamp
  "timestamp": 1592757181,
 curl -s 'localhost:8980/v2/blocks/7399860?pretty'|grep round-time
      "round-time": 1592742781,
```
Most notably, for my need, I'm using the /v2/accounts/XXX/transactions route.  The returned round time within the transaction is incorrect (local time).  As a 

...and those numbers converted from epoch UTC times...
```
fmt.Printf("%v\n", time.Unix(1592757181, 0)) 
fmt.Printf("%v\n", time.Unix(1592742781, 0)) 	
 ...
2020-06-21 16:33:01 +0000 UTC
2020-06-21 12:33:01 +0000 UTC
```

The correct time for the block (and the transactions within it) is 1592757181 -> 16:33:01

**Comment by brianolson** [comment]
Thanks for the report.
Confirmed on my local dev machine that lives in US/Eastern. However, on a server where the system timezone is UTC this bug doesn't happen. I tried running with environment `TZ=UTC` and that didn't work on my Mac and now I don't know if Go is getting the timezone from some clever Mac-specific syscall? (If you're running on Linux that might still be worth a try as a workaround.)

**Comment by patrickbsf** [comment]
Yup, it's still a bug.  :) 
Relying on 'local' time to be the same as UTC is definitely a bug.  Converting to/from UTC is built-in date/time functionality, so storing as UTC should be non-issue.
From scan of the PR, it seems that's really the issue.  The existing code called time.Unix(timestamp, 0) which returns the 'local' time for that epoch time.  Calling UTC() is correct fix.
