### ISSUE TITLE
Provide support for Indexer for a non archival node and only current state.

### ISSUE THREAD

**Issue by robert-zaremba** [algorand/indexer#1343]
## Problem

Today, the indexer requires Algorand archival node. This is a big requirement. Mainnet archival node is about 1.4TB.
Most of the apps only need to care about:
* current state
* current user balances
* current app smart-contract state

Often this is MB of data, not TB of data. Most of the Algorand dapps will require an indexer for a good user interface. Requiring Archival Node + Big Indexer is a huge infrastructure resource requirement.

## Solution

With this option enabled, allow to start indexer with a non archival node
+ the indexer should only index the "actual" data.
+ the indexer should be able to work with a non archival node
+ the indexer should (optionally) not sync with outdated state.
+ indexer should (optionally) remove past state and past transactions

**Comment by SilentRhetoric** [comment]
I will add that this becomes even more important with the addition of boxes, which are much easier to find, manage, and read from off-chain through an indexer.

**Comment by urtho** [comment]
So the indexer holds more data in "current state" than a node does - like deleted accounts, deleted account assets etc. One can have an indexer that stores only the current state without TX history but still the initial indexing requires access to the full TX archive to build this complete state along with deleted entities information.  

So this requests actually asks for a "catchup" mechanism where bootstrapping happens by downloading the state from a trusted source. Also whenever the indexer falls out of sync for more than 1000 rounds (like a >1hr maintenance) a full archival node would be required to sync it up to the current state as catchup nodes hold only 1k rounds. Or the indexer would need to source the rounds from the relays and skip the requirement of local node altogether.

**Comment by robert-zaremba** [comment]
Not really, IMHO, we should be able to start indexer at any moment. It won't sync the past state, only the current state, and there should be options what are we interesting in, eg list of token (or all of them), list of apps etc...

Consider the following use case:
I'm creating a dapp, and I'm only depending on bunch of ASA and my app sate. So I will start indexer a week before the lunch of the dapp. And I don't want to run archival node.

**Comment by madshapes-dev** [comment]
Can confirm there 100% is a need for a indexer that can query current state only. Main reason for it would be setup time (2+ weeks currently) and costs.

I think @urtho describes well how this could work. I mean we already have fast-catchup for the non-archival node - so a fast-catchup for indexer doesn't seem to improbable. It would come down to the sensitivity of the operations you are doing using this indexer, as you do have to trust the source for fast-catchup snapshot- but i guess it depends on the use-case.

**Comment by simonbelingar** [comment]
Can confirm there 100% is a need for a indexer that can query current state only. Main reason for it would be setup time (2+ weeks currently) and costs.

I think @urtho describes well how this could work. I mean we already have fast-catchup for the non-archival node - so a fast-catchup for indexer doesn't seem to improbable. It would come down to the sensitivity of the operations you are doing using this indexer, as you do have to trust the source for fast-catchup snapshot- but i guess it depends on the use-case.

**Comment by algoanne** [comment]
hey everyone, so I think conduit and follow mode basically solve what you're looking for here, though it's not exactly the same solution as described. Is there anything else needed that I'm missing? (if not I'll close this issue)

**Comment by robert-zaremba** [comment]
@algoanne , The indexer was updated and there is a new mode?

**Comment by algoanne** [comment]
@robert-zaremba yes - https://medium.com/algorand/lightweight-and-flexible-data-access-for-algorand-2051763ad8d0 
https://github.com/algorand/conduit
I'm sorry we didn't reach you with our release announcements!
