### ISSUE TITLE
Conduit documentation updates.

### ISSUE THREAD

**Issue by winder** [algorand/indexer#1368]
Another pass over the conduit documentation to make sure it is as clear and complete as possible for the initial preview release.

**Comment by barnjamin** [comment]
couple of the links in https://github.com/algorand/indexer/blob/develop/docs/Conduit.md#plugin-system 404

**Comment by barnjamin** [comment]
https://github.com/algorand/indexer/blob/develop/docs/conduit/plugins/filter_processor.md#config sample config at the bottom empty?

**Comment by barnjamin** [comment]
https://github.com/algorand/indexer/blob/develop/conduit/plugins/processors/filterprocessor/sample.yaml#L4 should ref to https://github.com/algorand/indexer/blob/develop/docs/conduit/plugins/filter_processor.md not `README.md`

**Comment by barnjamin** [comment]
https://github.com/algorand/indexer/blob/develop/docs/conduit/Development.md#implement-the-interface should probably direct the author to rebuild conduit, though if they're writing Go it's probably obvious

**Comment by barnjamin** [comment]
https://github.com/algorand/indexer/blob/develop/cmd/conduit/conduit.yml.example#L7 should not have a `-` 

https://github.com/algorand/indexer/blob/develop/cmd/conduit/conduit.yml.example#L18 should be `file_writer`

https://github.com/algorand/indexer/blob/develop/cmd/conduit/conduit.yml.example#L20 should not have a `-`
