### ISSUE TITLE
Cannot run indexer

### ISSUE THREAD

**Issue by andreysuslov95** [algorand/indexer#1391]
Hello everyone, I did follow the docs but could not figure it out how to run Indexer.
Guide: https://developer.algorand.org/docs/run-a-node/setup/indexer/

I'm trying to run indexer to populate my PostgreSQL database. My PostgreSQL is version 15 and runs in docker container with port 5436.

I try the following command:
./algorand-indexer daemon -P "host=0.0.0.0 port=5436 user=postgres password=pass dbname=postgres sslmode=disable" --algod=~/node/data --data-dir="/root/indexer/algorand-indexer_linux_amd64_2.15.0/datadir"

(running this command with host=localhost or host=127.0.0.1 gives the same error)

And get this error:
{"level":"info","msg":"Using configuration file: ","time":"2022-12-26T04:57:02-06:00"}
{"error":"~/node/data/algod.net: open ~/node/data/algod.net: no such file or directory","level":"error","msg":"fetcher setup, ~/node/data/algod.net: open ~/node/data/algod.net: no such file or directory","time":"2022-12-26T04:57:02-06:00"}

But when I run: cat ~/node/data/algod.net
It returns: 127.0.0.1:35529

How can I fix this?

**Comment by algorandskiy** [comment]
It looks like `~/node/data` was not expanded to the full path by your cmd interpreter. I suggest replacing it with a full path, or trying a command below:
```
./algorand-indexer daemon -P "host=0.0.0.0 port=5436 user=postgres password=pass dbname=postgres sslmode=disable" --algod-net=http://$(cat ~/node/data/algod.net) --algod-token=$(cat ~/node/data/algod.token)  --data-dir="/root/indexer/algorand-indexer_linux_amd64_2.15.0/datadir"
```

**Comment by andreysuslov95** [comment]
That works! Thank you 👍
