### ISSUE TITLE
Move block generator to its own repo

### ISSUE THREAD

**Issue by algoanne** [algorand/indexer#1404]
Move block generator to its own repository, and use the AGPL license. block generator will continue to depend on go-algorand. 

Users will thus still be able to use the block generator binary to generate block data, and then use this data in any project (of any license, without polluting their license). 

Out of scope: refactor block generator to use the state delta endpoint from algod.

**Comment by winder** [comment]
Closed by https://github.com/algorand/internal-tools/commit/1d6586f8e514d90bc0e77a85f9677928f462db6e
