### ISSUE TITLE
[License] Update go-algorand-sdk and algod api to include voting data 

### ISSUE THREAD

**Issue by AlgoStephenAkiki** [algorand/indexer#1407]
Currently the function convertTrimmedLcAccountData in encoding.go can not fully convert to the baseAccountData struct because it is missing information required.  Currently, we are going to "shim" these values with default values until the proper sdk can be updated.  It is understood that some unit tests will fail while doing this.

This is for the conversion of idb/postgres/internal/writer/writer.go:AddBlock(block *sdk.Block, delta ledgercore.StateDelta) conversion.

**Comment by Eric-Warehime** [comment]
It looks like the fields we were concerned about are [VoteID](https://github.com/algorand/go-algorand/blob/master/ledger/ledgercore/accountdata.go#L55) and [SelectionID](https://github.com/algorand/go-algorand/blob/master/ledger/ledgercore/accountdata.go#L56). 

Those fields are equivalent to [VoteParticipationKey](https://github.com/algorand/go-algorand-sdk/blob/a935089a4bb5e07ca223a17f28114e179be94243/client/v2/common/models/account_participation.go#L24) and [SelectionParticipationKey](https://github.com/algorand/go-algorand-sdk/blob/a935089a4bb5e07ca223a17f28114e179be94243/client/v2/common/models/account_participation.go#L8) in the SDK.

**Comment by shiqizng** [comment]
> It looks like the fields we were concerned about are [VoteID](https://github.com/algorand/go-algorand/blob/master/ledger/ledgercore/accountdata.go#L55) and [SelectionID](https://github.com/algorand/go-algorand/blob/master/ledger/ledgercore/accountdata.go#L56).
> 
> Those fields are equivalent to [VoteParticipationKey](https://github.com/algorand/go-algorand-sdk/blob/a935089a4bb5e07ca223a17f28114e179be94243/client/v2/common/models/account_participation.go#L24) and [SelectionParticipationKey](https://github.com/algorand/go-algorand-sdk/blob/a935089a4bb5e07ca223a17f28114e179be94243/client/v2/common/models/account_participation.go#L8) in the SDK.
I believe this is correct. 
```
apiParticipation = &model.AccountParticipation{
			VoteParticipationKey:      record.VoteID[:],
			SelectionParticipationKey: record.SelectionID[:],
			VoteFirstValid:            uint64(record.VoteFirstValid),
			VoteLastValid:             uint64(record.VoteLastValid),
			VoteKeyDilution:           uint64(record.VoteKeyDilution),
}
```
https://github.com/algorand/go-algorand/blob/master/daemon/algod/api/server/v2/account.go#L70-L76
