### ISSUE TITLE
Can't start indexer

### ISSUE THREAD

**Issue by zhangpeizheng123** [algorand/indexer#1410]
When I start the indexer,I got this error:

{"error":"openPostgres() err: getMigrationState() get state err: GetMetastate() err: ERROR: relation \"metastate\" does not exist (SQLSTATE 42P01)","level":"error","msg":"could not init db, openPostgres() err: getMigrationState() get state err: GetMetastate() err: ERROR: relation \"metastate\" does not exist (SQLSTATE 42P01)","time":"2023-01-10T17:46:47+08:00"}

I don't know what's wrong with the indexer or my postgres db is not installed correctly,  any suggestions would be appreciated!

**Comment by zhangpeizheng123** [comment]
Thanks, problems are solved!

**Comment by n1ck47** [comment]
@zhangpeizheng123  I'm having the same problem, how did you solve it?

**Comment by hesyar** [comment]
would be great if you tell us how you solved it
