### ISSUE TITLE
Query performance for GET Asset/{asset-id}/transactions - 3+minutes 

### ISSUE THREAD

**Issue by purestaketdb** [algorand/indexer#142]
Seeing extreme slowness with queries to the GET asset/{asset-id}/transactions - Running Indexer on AWS RDS Postgres - db.r5.large (2 vpcu, 16gb RAM)

Because API queries all time out and introduce a layer in-between, tests below are run directly with psql on the instance. Using TestNet, 3797 is the Algorand developer coin. 

```sql
testnet=> SELECT t.round, t.intra, t.txnbytes, t.extra, t.asset, h.realtime FROM txn t JOIN block_header h ON t.round = h.round WHERE t.asset = 3797 ORDER BY t.round, t.intra LIMIT 5;
Time: 772619.272 ms (12:52.619)
```

```sql 
testnet=> EXPLAIN SELECT t.round, t.intra, t.txnbytes, t.extra, t.asset, h.realtime FROM txn t JOIN block_header h ON t.round = h.round WHERE t.asset = 3797 ORDER BY t.round, t.intra LIMIT 5;
                                             QUERY PLAN                                              
-----------------------------------------------------------------------------------------------------
 Limit  (cost=1.00..196226.07 rows=5 width=322)
   ->  Nested Loop  (cost=1.00..152937822.88 rows=3897 width=322)
         ->  Index Scan using txn_pkey on txn t  (cost=0.57..152906193.23 rows=3897 width=314)
               Filter: (asset = 3797)
         ->  Index Scan using block_header_pkey on block_header h  (cost=0.43..8.12 rows=1 width=16)
               Index Cond: (round = t.round)
(6 rows)
```

Running without the limit does speed it up, to 3 minutes - 

```sql
testnet=> SELECT t.round, t.intra, t.txnbytes, t.extra, t.asset, h.realtime FROM txn t JOIN block_header h ON t.round = h.round WHERE t.asset = 3797 ORDER BY t.round, t.intra;
Time: 191930.111 ms (03:11.930)
```

```sql 
testnet=> EXPLAIN SELECT t.round, t.intra, t.txnbytes, t.extra, t.asset, h.realtime FROM txn t JOIN block_header h ON t.round = h.round WHERE t.asset = 3797 ORDER BY t.round, t.intra;
                                                QUERY PLAN                                                 
-----------------------------------------------------------------------------------------------------------
 Gather Merge  (cost=10168782.11..10169161.07 rows=3248 width=322)
   Workers Planned: 2
   ->  Sort  (cost=10167782.09..10167786.15 rows=1624 width=322)
         Sort Key: t.round, t.intra
         ->  Nested Loop  (cost=0.43..10167695.49 rows=1624 width=322)
               ->  Parallel Seq Scan on txn t  (cost=0.00..10154514.44 rows=1624 width=314)
                     Filter: (asset = 3797)
               ->  Index Scan using block_header_pkey on block_header h  (cost=0.43..8.12 rows=1 width=16)
                     Index Cond: (round = t.round)
(9 rows)
```

**Comment by brianolson** [comment]
txn.asset isn't indexed; try adding one?
`CREATE INDEX IF NOT EXISTS txn_by_asset ON txn ( asset );`

**Comment by purestaketdb** [comment]
That absolutely worked - the same query completed in 69ms for the unlimited and 9ms for the limit 5. I'll add to all the clusters. 

Note, CREATE INDEX is locking, the CONCURRENTLY option may be useful for folks already in production 

`CREATE INDEX CONCURRENTLY IF NOT EXISTS txn_by_asset ON txn ( asset );`

**Comment by pbennett** [comment]
Should this really be closed?  I'd think we'd want to add this index to all new/existing indexer DBs as a migration?  
All queries used by the API should be extremely efficient out of the box.

**Comment by brianolson** [comment]
The Indexer is designed to avoid premature optimization by adding too many indexes and this kind of customization for the specific workload you care about is intended. We'll call out in the release notes any global schema & index changes so people can follow along if they've customized their PostgreSQL environment.

**Comment by pbennett** [comment]
I'm not sure I follow, there is an explicit API call provided by the indexer to get a list of all transactions for an asset, and the asset of a transaction isn't indexed at all - forcing a full table scan for a base-level API call.
This is the very thing a database is designed for and in this case, this specific API call.  
If people are writing their own queries, fine, but this is the indexer itself making this call for its own API.  That API should be performant out of the box.   Isn't that the entire point of the indexer?
I don't understand why this would be a customers' installation-specific requirement.
