### ISSUE TITLE
Indexer performance

### ISSUE THREAD

**Issue by algorotem** [algorand/indexer#143]
Indexer has some performance issues with specific calls. There is a need to gather more information and understand how to guarantee good performance on all API calls. 
Subtasks - 
1. Run performance tests on all the end-points and understand which ones are lacking.
2. Get a list of the indices/solutions that will solve these and their size + growth potential
3. Decide which ones will be added to the out of the box version and which ones will go to the Ops section

**Comment by winder** [comment]
note: In addition to performance tests on each endpoint, the parameters used for each will have different performance. For example date, asset filters, and asset balance filters are probably slow. But we don't know how slow.

**Comment by brianolson** [comment]
in progress
https://github.com/brianolson/indexer/tree/speedtest
