### ISSUE TITLE
validator: support validating box data.

### ISSUE THREAD

**Issue by winder** [algorand/indexer#1432]
## Problem

[Validator](https://github.com/algorand/indexer/tree/develop/cmd/validator) is used to confirm that the postgres data is consistent with data returned by go-algorand.

It should be updated to validate box data along with the account data. 

## Urgency

High. If there is an inconsistency with production data we would not currently be able to detect it.

**Comment by bbroder-algo** [comment]
https://github.com/algorand/indexer/pull/1517

**Comment by bbroder-algo** [comment]
Validator logic merged into indexer, however
1: requested --resource capability for redirects back into validator
2: round response incorporated into algod's box endpoint
3: round REQUEST incorporated into algod's box endpoint

**Comment by bbroder-algo** [comment]
2: https://github.com/algorand/go-algorand/pull/5340

**Comment by bbroder-algo** [comment]
checking the round response in the validator #1564

**Comment by gmalouf** [comment]
Completed with #1517
