### ISSUE TITLE
indexer v. algod nightly test is likely broken

### ISSUE THREAD

**Issue by tzaffi** [algorand/indexer#1495]
### Broken Nightly Test - Re-imagine or Just Remove

We can see that the nightly `indexer v. algod` test [is failing](https://app.circleci.com/pipelines/github/algorand/indexer/3625/workflows/26c91039-e34d-4f98-8f88-ff62d39158ac/jobs/5093). This is because the `go-algorand` submodule dependency has [been removed](https://github.com/algorand/indexer/pull/1492) (though the error on Circle seems to obscure this).

I don't know if the test even makes sense anymore, but before removing, we ought to assess whether it is worth to keep some version of it.

**Comment by tzaffi** [comment]
@shiqizng and @winder have noted that this is not obsolete, so the job needs to be amended / rethought

**Comment by winder** [comment]
This is hopefully addressed by https://github.com/algorand/indexer/pull/1496#pullrequestreview-1326563782

**Comment by tzaffi** [comment]
Ok, so the error I was seeing is the real error.
