### ISSUE TITLE
Build: E2ETests cannot run against go-algorand stable when config version in the nightly build differs

### ISSUE THREAD

**Issue by gmalouf** [algorand/indexer#1547]
### Subject of the issue

If the config version in the nightly build is greater than the version supported in stable, `make e2e` cannot run as Algod will fail on configuration mismatch.

This is because `CI_E2E_FILENAME` always points to some form of rel-nightly - we don't seem to have a way to pull a rel-stable config today based on a skim of the Python setup code and S3 bucket.

## Ideas to Address

1. Have a way to set the config and binary channels simultaneously/next to eachother to match (whether stable or nightly).
2. Need the ability to pull a stable release config, even if just using defaults in the binary perhaps?

**Comment by algoanne** [comment]
closing in favor of #1554
