### ISSUE TITLE
Some inner PAY transactions have incorrect metadata.

### ISSUE THREAD

**Issue by urtho** [algorand/indexer#1561]
### Subject of the issue

There are around 80K inner transactions with incorrect metadata in the indexer.
Parent's JSON has all the correct inners but the companion rows with root pointing to this parent 
are missing PAY metadata resulting in missing receiver address and amount (or other info in case of close)
Typeenum is OK but other data is missing/incorrect.

Example row:
`select * from txn where round = 19378233 and intra = 154` 

This has no impact on indexer API as inners are sourced from parent's metadata not from rows with TXID==NULL. 
But SQL data is incorrect for at least ~80K rows. 

### Expected behaviour

TX rows with standalone inners should have matching metadata instead of the parent's partial APP call metadata.

**Comment by urtho** [comment]
The issue seems to exist only for some old round range : 17431491..19619148
Maybe reindexing from scratch is going to solve this for me.

**Comment by winder** [comment]
This resulted from a bug fixed in Indexer 2.8.3 (early 2022). Inner transaction data written prior to that release has the wrong transaction data. There are some details here: https://github.com/algorand/indexer/issues/1292

**Comment by urtho** [comment]
Yeah - so my bad - I did not reindex after the bugfix.
