### ISSUE TITLE
Timeout iterating through account transactions

### ISSUE THREAD

**Issue by AndrewMerriganIE** [algorand/indexer#1577]
### Subject of the issue
When iterating through an account with a large number of transactions using the indexer the eventually I hit a point where queries timeout. Read/Write timeouts are set to 60s so timeout occurs around the 60s mark. any guidance on this would be appreciated.

`{
    "message": "error while searching for transaction: timeout during call"
}`

### Your environment
* indexer 2.15.4
* PostgreSQL 14.7 vCPUs: 4 Memory: 16 GB
* I've added the indexes from https://github.com/algorand/indexer/blob/main/docs/PostgresqlIndexes.md

### Steps to reproduce

1. GET /accounts/RANDGVRRYGVKI3WSDG6OGTZQ7MHDLIN5RYKJBABL46K5RQVHUFV3NY5DUE/transactions?limit=100&next=H6d2AQAAAABKAAAA

### Expected behaviour
A page of transactions with the next page token

### Actual behaviour
`{
    "message": "error while searching for transaction: timeout during call"
}`

**Comment by urtho** [comment]
This request translates to query:
```sql
SELECT 
	t.round, t.intra, t.txn, root.txn, t.extra, t.asset FROM txn t JOIN txn_participation p ON t.round = p.round AND t.intra = p.intra LEFT OUTER JOIN txn root ON t.round = root.round AND (t.extra->>'root-intra')::int = root.intra 
  WHERE p.addr = '\x881a335631c1aaa46ed219bce34f30fb0e35a1bd8e1490802be795d8c2a7a16b' AND t.round <= 24553246 ORDER BY p.addr, p.round DESC, p.intra DESC LIMIT 86
```
This query times out on any reasonable Postgres setup. 

Adding a filter on p.round makes for proper use of the txn_participation index:

```sql
SELECT 
	t.round, t.intra, t.txn, root.txn, t.extra, t.asset FROM txn t JOIN txn_participation p ON t.round = p.round AND t.intra = p.intra LEFT OUTER JOIN txn root ON t.round = root.round AND (t.extra->>'root-intra')::int = root.intra 
  WHERE p.addr = '\x881a335631c1aaa46ed219bce34f30fb0e35a1bd8e1490802be795d8c2a7a16b'  AND p.round <= 24553246 AND t.round <= 24553246 ORDER BY p.addr, p.round DESC, p.intra DESC LIMIT 86  
```

**Comment by AndrewMerriganIE** [comment]
Thanks for the response, ok so if i wanted to iterate back through all the txsof an account I'd need to add a decreasing round to the curl command probably just the round from the continuation token minus a constant.

**Comment by urtho** [comment]
pagination or round range filter on this endpoint combined with address filter is not using indexes and will timeout no matter what you do. 
This needs a fix in the indexer code.
