### ISSUE TITLE
Algorand Indexer sync stopped at block 30077385

### ISSUE THREAD

**Issue by Palak3196** [algorand/indexer#1584]
Hi Team,

We have been running an Algorand indexer v2 using: https://developer.algorand.org/docs/run-a-node/setup/indexer/
However the algorand indexer has stopped syncing at 30077385 while our algorand node is syncing fine ahead.

What should be my migration steps?

Thanks,
Palak

**Comment by urtho** [comment]
Are you using the 2.15.4 version ?

**Comment by Palak3196** [comment]
Yes

**Comment by gmalouf** [comment]
Closing, as everyone had to move to 3.x as of the last consensus upgrade in January.
