### ISSUE TITLE
 event not found

### ISSUE THREAD

**Issue by block98ct** [algorand/indexer#1609]
./algorand-indexer daemon --data-dir /tmp -P "host=[127.0.0.1] port=[5432] user=[root] password=[my_password] dbname=[aperion] sslmode=disable"  --no-algod
bash: !]: event not found

**Comment by urtho** [comment]
You probably have ! (exclamation point) in your DB password.

try using single quotes :

./algorand-indexer daemon --data-dir /tmp -P 'host=[127.0.0.1] port=[5432] user=[root] password=[my_password] dbname=[aperion] sslmode=disable' --no-algod

**Comment by block98ct** [comment]
@urtho I have removed double quotes  because my password had a "!" mark 
I ran the command I got this error
Error: unknown flag: --no-algod

{"error":"unknown flag: --no-algod","level":"error","msg":"an error occurred running indexer","time":"2024-04-26T15:44:18+05:30"}

After removing --no-algod  flag run the command got another error



{"error":"openPostgres() err: getMigrationState() get state err: GetMetastate() err: ERROR: relation \"metastate\" does not exist (SQLSTATE 42P01)","level":"error","msg":"unable to open database, if tables are not initialized ensure Conduit is running","time":"2024-04-26T15:45:56+05:30"}

**Comment by urtho** [comment]
--no-algod is not longer supported in v3 indexer.

You are running an Indexer API which needs to connect to a synchronized database.
To synchronize a DB you need to run Conduit and a follower node. 
Sychnronization will take about 2 to 4 weeks and use around 2.7 TB for the database - unless you intend to filter transactions in Conduit.

**Comment by block98ct** [comment]
I want to run Node and sync that data in PostgreSQL. How can I do it?
do you know any way?
@urtho

**Comment by gmalouf** [comment]
This is more of a support issue, suggest checking out https://github.com/algorand/conduit/blob/master/docs/tutorials/IndexerWriter.md or the [Algorand Discord channe](https://discord.gg/invite/algorand)l to get additional support.
