### ISSUE TITLE
v2/accounts endpoint returns repeated assets for specific account

### ISSUE THREAD

**Issue by tolgacanunal** [algorand/indexer#162]
The endpoint is returning the same **asset object** under **assets** variable.

This issue is only reproducible for this account below. 
(**RL6VDLXCN5G7N2GRTS7YLVDSFT4PVBBUOVTVS7T26OQ5MLXYQKRMI5ADXY**)

```
curl --location --request GET 'https://indexer-testnet.aws.algodev.network/v2/accounts/RL6VDLXCN5G7N2GRTS7YLVDSFT4PVBBUOVTVS7T26OQ5MLXYQKRMI5ADXY' \
--header 'X-Indexer-API-Token: KegWFLYQnBNVeP4oHCX64dObBk8VemzYdNqsnAOIxYQ8aqJLQTYeVDQyZNnx1PZA'
```

Example JSON file [here](https://gist.github.com/tolgacanunal/2fda33a547ea879dafe4d76586ae89cd)

**Comment by winder** [comment]
This issue seems to have been resolved with one of the fixes that went into the last release. Thanks @tolgacanunal for the report!
