### ISSUE TITLE
Incentives: Add a way to lookup the blocks proposed by an address

### ISSUE THREAD

**Issue by jasonpaulos** [algorand/indexer#1623]
## Problem

With the upcoming release of participation incentives, users will want to track the incentives that an individual account accrues over time.

Incentives are not transferred by transactions, so existing transaction lookup endpoints can't solve this problem. Instead this information is present in the block header.

## Solution

A solution is to have a new endpoint which takes an account address as an argument and returns information about all blocks proposed by that address, likely in a paginated list with the most recent blocks first.

As for the information about individual blocks being returned, the following are both possibilities:
1. Return the entire block header
2. Return only the relevant fields related to incentives as a subset of information about the block header

Depending on the expected use cases, one of these may make more sense than the other.

## Dependencies

An index on block proposers would help make the suggested endpoint more efficient.

## Urgency

Good to think about before incentives are live on mainnet

**Comment by urtho** [comment]
Nodely  will have a PR with this soon. 
The implementation is live on  FNet.

playground: 
https://nodely.io/swagger/index.html?url=/swagger/api/fnet/indexer.oas3.yml#/search/searchForBlocks

More here: 
https://github.com/AlgoNode/indexer-api-cdb/issues/9

**Comment by emg110** [comment]
What a powerhouse Nodely is! Wow!
Is it possible that using an argument the endpoint returns one of full block header or incentive-related fields? I mean for both return possibilities to be present and differ using an argument like "full_header"? That will be awesome @urtho

**Comment by emg110** [comment]
If the implementation and development resource cost on having such a _full header param is relatively affordable, I would say yes, it makes  a difference and would be a very practical option for devs to use.
