### ISSUE TITLE
Incentives: Account rewinding does not account for participation rewards

### ISSUE THREAD

**Issue by jasonpaulos** [algorand/indexer#1625]
## Problem

Participation incentives are an upcoming feature, and incentives are not transferred by transactions.

This will be a problem for the account rewinding logic, since the `AccountAtRound` has no way of accounting for participation rewards: https://github.com/algorand/indexer/blob/316221e01269ced80b76a3b4ea72a9ce0cb28296/accounting/rewind.go#L67

## Solution

While modifying the `AccountAtRound` function to properly account for participation rewards is a valid solution, it's worth considering whether it makes more sense to disable/remove this feature, or adjust our documentation/messaging around the expectations here. This feature has not been updated in a long time, and there are many other scenarios it cannot support.

Generally speaking, failing is better than producing incorrect information.

## Dependencies

n/a

## Urgency

Good to address before incentives are active on mainnet.

**Comment by gmalouf** [comment]
Noting: Check SDKs for support/use of account rewind and update there prior to releasing indexer breaking change.
