### ISSUE TITLE
transaction response come back with two similar fields 

### ISSUE THREAD

**Issue by algorotem** [algorand/indexer#163]
For example 
https://indexer-mainnet.aws.algodev.network/v2/transactions?txid=IWKY4XBCAJGZIIYJOJKTQ2SLY6DH27QL72ZHSOKMHIBHFVN5YDPQ

returns `close-rewards` and `closing-rewards` is that the same field?

**Comment by winder** [comment]
this is probably a bug and we'll need to fix close-amount / deprecate closing-amount

**Comment by winder** [comment]
Related to #971

**Comment by chaihoang** [comment]
Duplicate of #971
