### ISSUE TITLE
transactions/{txid} doesn't return the transaction 

### ISSUE THREAD

**Issue by algorotem** [algorand/indexer#164]
what call did I make?
`https://indexer-mainnet.aws.algodev.network/v2/transactions/IWKY4XBCAJGZIIYJOJKTQ2SLY6DH27QL72ZHSOKMHIBHFVN5YDPQ`

what do I expect to get?
the transaction data

what did I get in practice?
`404 not found`

**Comment by brianolson** [comment]
`https://indexer-mainnet.aws.algodev.network/v2/transactions?txid=IWKY4XBCAJGZIIYJOJKTQ2SLY6DH27QL72ZHSOKMHIBHFVN5YDPQ`

**Comment by algorotem** [comment]
I'm aware of this option but it's inconsistent with the rest.

**Comment by brianolson** [comment]
txid is not the primary key and must not be treated as such
