### ISSUE TITLE
Rewards are always 0

### ISSUE THREAD

**Issue by fabrice102** [algorand/indexer#166]
The `rewards` field of each account is always 0 even when rewards were received:

Concretely
```bash
$ curl -s "localhost:8980/v2/accounts/SN3FSQVLLNWSI3I7QCMQEQN6L42OW5RP4FNM6BNOZHBRKHODSQYU4MUPKE" | jq
```
returns
```json
{
  "account": {
    "address": "SN3FSQVLLNWSI3I7QCMQEQN6L42OW5RP4FNM6BNOZHBRKHODSQYU4MUPKE",
    "amount": 882040798,
    "amount-without-pending-rewards": 882040798,
    "assets": [
      {
        "amount": 1844000079218796,
        "asset-id": 2512768,
        "creator": "",
        "is-frozen": false
      }
    ],
    "created-assets": [
      {
        "index": 2512768,
        "params": {
          "clawback": "SN3FSQVLLNWSI3I7QCMQEQN6L42OW5RP4FNM6BNOZHBRKHODSQYU4MUPKE",
          "creator": "SN3FSQVLLNWSI3I7QCMQEQN6L42OW5RP4FNM6BNOZHBRKHODSQYU4MUPKE",
          "decimals": 6,
          "default-frozen": false,
          "freeze": "SN3FSQVLLNWSI3I7QCMQEQN6L42OW5RP4FNM6BNOZHBRKHODSQYU4MUPKE",
          "manager": "SN3FSQVLLNWSI3I7QCMQEQN6L42OW5RP4FNM6BNOZHBRKHODSQYU4MUPKE",
          "metadata-hash": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
          "name": "YouNow Pending Props",
          "reserve": "SN3FSQVLLNWSI3I7QCMQEQN6L42OW5RP4FNM6BNOZHBRKHODSQYU4MUPKE",
          "total": 1844674407370955,
          "unit-name": "xPROPS",
          "url": "https://propsproject.com/"
        }
      }
    ],
    "pending-rewards": 0,
    "reward-base": 134204,
    "rewards": 0,
    "round": 8208842,
    "sig-type": "sig",
    "status": "Offline"
  },
  "current-round": 8208842
}
```

**Comment by brianolson** [comment]
Indexer has made no attempt to track 'the sum of all rewards for an account'. This can be a feature request for the future.

**Comment by fabrice102** [comment]
What is the field `rewards` representing?

**Comment by brianolson** [comment]
When `algod` returns that field it has the sum of all rewards an account has received. Indexer was initially focused on providing new functionality (search of transaction history) and didn't recreate that statistic.

**Comment by pbennett** [comment]
It seems like it should include at least the same data as is available from the local node.  All the indexer needs to do is update the account record with the latest value as it updates everything else.  Latest block wins.    If the indexer doesn't return equivalent data to just calling the node itself and the /v1/account/xxx route, that seems a very unusual omission.
The fact that it actually returns the rewards property and returns it as 0 (when it isn't) is even more striking (and IMO a bug).  It should either return the correct value or not return it at all.

**Comment by fabrice102** [comment]
Maybe the best short-term solution

**Comment by algorotem** [comment]
I agree. It is a bug and will get fixed as soon as possible. 
Many thanks for catching it.

**Comment by roccomuso** [comment]
This should be addressed asap, any news?

**Comment by brianolson** [comment]
simple fix: make "rewards" field on account optional. `algod` will set it and `algorand-indexer` will not set that member of the json dict. Then there won't be the confusing zero.

**Comment by roccomuso** [comment]
Can we have `rewards` returning the right value for the accounts instead of getting rid of that field?

**Comment by winder** [comment]
@roccomuso we're going to support rewards with indexer. It's been prioritized and we'll start working on it soon.

**Comment by ian-algorand** [comment]
This issue is being handled in the current sprint. Should have a solution within a week.

**Comment by winder** [comment]
This is now implemented in the develop branch.

**Comment by roccomuso** [comment]
when this will be in the prod release?

**Comment by winder** [comment]
@roccomuso it looks like this isn't going to make it into the next release due to how long it takes to update historical rewards data. I need to do improve the update logic so that it can happen in the background instead of blocking indexer while the migration happens. I don't have an ETA for when it will make it into a release, but am optimistic that it wont take more than another week or two.

**Comment by roccomuso** [comment]
@winder Any update on this?

**Comment by roccomuso** [comment]
@winder can you confirm this is fixed and available in the current release?

**Comment by winder** [comment]
@roccomuso confirmed.
