### ISSUE TITLE
switch to live algod e2e test

### ISSUE THREAD

**Issue by brianolson** [algorand/indexer#170]
task: run buildtestdata.sh and upload a net_done.tar.bz2 file
switch travis config to run misc/e2elive.py instead of misc/e2etest.py

**Comment by ian-algorand** [comment]
Hey Brian, Rotem is asking for more information on this.

**Comment by brianolson** [comment]
The current misc/e2etest.py uses the sqlite3 files from `algod` and parses them in Python and compares that to Indexer API results. This effectively means Python code has to re-create the algod API, and this is annoying to maintain and keep in sync.
New test script misc/e2elive.py runs `algod` against a tarred up frozen private network (the same one as e2etest, based on go-algorand/test/scripts/e2e_client_runner.py) and compares `algod` API values to Indexer API values. Especially since API reunification, they should provide the same results. This should be more sustainable in the future.

**Comment by yaovi-a** [comment]
@brianolson , to confirm if this is done.
