### ISSUE TITLE
Indexer serving stats

### ISSUE THREAD

**Issue by brianolson** [algorand/indexer#174]
Keep counters of number of times each URL handler is accessed and sum of milliseconds spent serving.
This should help determine if a query has become frequent such that it needs to be optimized by adding a database index or other measures.
Serve on /v2/serverstats or similar.
```json
{
 "/v2/accounts":{
    "count": 123,
    "ms": 31337
  },
  ...
}
```

**Comment by algorotem** [comment]
I believe that it shouldn't live in Indexer. This information can be
(and is) retrieved from Nginx / aws / etc.

**Comment by winder** [comment]
We could easily add this if we wanted to:

This one has system stats, which do make sense to record at the application level 
https://github.com/tkitsunai/echo-stats-handler
```
{
  time: 1522261688402036500,
  go_version: "go1.10",
  go_os: "darwin",
  go_arch: "amd64",
  cpu_num: 4,
  goroutine_num: 3,
  gomaxprocs: 4,
  cgo_call_num: 1,
  memory_alloc: 409680,
  memory_total_alloc: 409680,
  memory_sys: 4262136,
  memory_lookups: 5,
  memory_mallocs: 4957,
  memory_frees: 101,
  memory_stack: 360448,
  heap_alloc: 409680,
  heap_sys: 1736704,
  heap_idle: 761856,
  heap_inuse: 974848,
  heap_released: 0,
  heap_objects: 4856,
  gc_next: 4473924,
  gc_last: 0,
  gc_num: 0,
  gc_per_second: 0,
  gc_pause_per_second: 0,
  gc_pause: [ ]
}
```

There is also (several) prometheus middleware options which might have endpoint metrics
https://echo.labstack.com/middleware/prometheus
https://github.com/0neSe7en/echo-prometheus
https://github.com/globocom/echo-prometheus

```
