### ISSUE TITLE
Getting genesis.json

### ISSUE THREAD

**Issue by ksemaev** [algorand/indexer#177]
Since my coin node is on one instance/container and indexer is on another maybe you can place default `genesis.json` in this repo? 
What is the recommended way to get a default one?

**Comment by winder** [comment]
@ksemaev you need the genesis.json for whichever network you are connecting to, there is no default. Currently you need to fetch it from your node's data directory, which is pretty annoying if you are using containers.

I've done some experimenting with docker-compose and had to workaround this issue by creating a shared volume whose only purpose was sharing the genesis.json file between containers.

In the future I plan to add an endpoint to algod for fetching the genesis.json which should be a much cleaner solution.
