### ISSUE TITLE
Consider standard json log output

### ISSUE THREAD

**Issue by ksemaev** [algorand/indexer#179]
Current logs are like:
```
will start from round >1360401
round r=1360402 (0 txn) imported in 18.454454ms
```

There's even to timestamp. Can you please use some standard logging libs, cause it's very hard to work with such log output

**Comment by ksemaev** [comment]
Also please add loglevel cli args or config options

**Comment by winder** [comment]
This has been started, the logrus object is being passed around to all the important objects. We still need to change log/print calls to use the object.
