### ISSUE TITLE
Unexpected DB Migration

### ISSUE THREAD

**Issue by winder** [algorand/indexer#187]
## Summary
In a multi-reader postgres configuration I've been running a node with no algod parameters expecting it to effectively be in read-only mode. It turns out if there is a DB migration, the migration will be attempted regardless.

## Scope
This could be solved in a couple ways:
1) require a specific '--perform-migration' option, without which the migration will not be performed.
2) ~if there are no algod settings generate an error, so that the user must either set `--no-algod` (putting the daemon in read-only mode), or they must provide the algod settings (allowing a proper migration, if algod is needed for the migration).~

## Urgency
It's really easy to accidentally break the indexer DB without this feature. We should fix asap to avoid people breaking

**Comment by ian-algorand** [comment]
Decided to go with the first approach, and to also detect if a migration is actually needed. If it's needed, throw an error and mention the new flag.

**Comment by brianolson** [comment]
read-only mode, or no-algod mode, should definitely imply no-migrations

**Comment by brianolson** [comment]
but with-algod mode, implying being a writer, should automatically do migrations (unless maybe --no-migrations is set? but I'm skeptical of the value of deliberately being stuck in the past with known bugs)

**Comment by winder** [comment]
@brianolson the main thing is that we need to make it harder to accidentally have multiple nodes perform migrations. With the proposed solution it will be much harder because there's a special flag needed for the "migrator". The`/health` endpoint should display something to the effect of "this DB needs a migration" to hopefully let the admin know they need to do a migration, and inform users that the data is stuck in the past for some reason.

**Comment by brianolson** [comment]
The normal case is to have one indexer. One writer indexer and several read-only indexers shouldn't be that hard to manage. I don't want to waste too much time preventing against operator error (multiple writers) especially when solving that right is a hard problem with little reward. I think doing migrations is the right default action and requiring to add "--actually-do-migrations" will make operation harder for more users and will leave databases unmigrated and mysteriously failing. If someone upgrades the software I don't want them to be left with the question, "I upgraded, why is it broken and not upgraded?"
