### ISSUE TITLE
Cannot GET /v2/accounts/<address>

### ISSUE THREAD

**Issue by roccomuso** [algorand/indexer#189]
I got this error while calling `/V2/accounts/:address` API on an address.

>     "message": "failed while searching for account: account_round err pq: cannot cast type jsonb to bigint"

What does it means? Is it a bug?

**Comment by brianolson** [comment]
That happens when the Indexer is running on Postgres of an older version. Do you know what version of postgres the server is running? I think it's tested most on >= 11.5 might should work on >= 11.0

**Comment by roccomuso** [comment]
Thanks!
