### ISSUE TITLE
High I/O Wait times since upgrading to 2.1.1

### ISSUE THREAD

**Issue by jecassis** [algorand/indexer#193]
Since upgrading to 2.1.1, began to see unusually large `iowait` percentages. Not since the initial migration to v2 have we seen such utilization:

```
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           9.03    0.00    6.49   42.83    0.10   41.54

Device             tps    kB_read/s    kB_wrtn/s    kB_read    kB_wrtn
sda            1525.90    101767.59       257.90 10699734039   27114938
```

In our case the utilization is coming from this process:

```
postgres  14xx  3.1  2.7 425880 225156 ?       Ds   Sep01  55:10  \_ postgres: 12/main: algorand pgdb 127.0.0.1(49538) SELECT
```

And we are seeing high import times, too:
```
algorand-indexer[14yy]: will start from round >8842225
algorand-indexer[14yy]: accounting updated through round 8842226
algorand-indexer[14yy]: round r=8842226 (32 txn) imported in 609.294487ms
algorand-indexer[14yy]: will start from round >8842226
```

There is no one running queries on the DB through the API most of the time so we assume all that activity is due to synchronizing with `algod`.

If there is something not working correctly in our configuration, where would one look in order to root cause it?

**Comment by jecassis** [comment]
Something we cannot yet explain just happened. For the last hour, after close to 50 hours of the unusual behavior, it has gone back to a normal-looking state:

From `iostat`:

```
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          21.61    0.00    9.90   14.32    0.26   53.91

Device             tps    kB_read/s    kB_wrtn/s    kB_read    kB_wrtn
sda              57.00       272.00       616.00        272        616
```

And notably from `ps`, this process is no longer permanently on `SELECT`/`D` state but in `idle`/`S` state:

```
postgres  14xx  3.0  2.7 425888 225196 ?       Ss   Sep01  56:06  \_ postgres: 12/main: algorand pgdb 127.0.0.1(49538) idle
```

Was there a database schema change or scrub in the update?

**Comment by winder** [comment]
This is most likely due to a database migration, we need to figure out a way to make these processes more visible
