### ISSUE TITLE
migration testing

### ISSUE THREAD

**Issue by brianolson** [algorand/indexer#195]
Full testing of migrations would check out Indexer at each of the last N releases, import some data (appropriate data, nothing too new that needs protocol upgrades not in the prior release), and then run migrations from there to the current development state of Indexer.
This is a big pile of scripting and making a per-release archive of data blobs to import.

**Comment by winder** [comment]
The scripting part of this is done, it is **test/migrations/postgres_migration_test.sh**

**Comment by winder** [comment]
These old migrations have been deprecated, and the new ones have tests!
