### ISSUE TITLE
Problem parsing application txs with release 2.1.1

### ISSUE THREAD

**Issue by mxmauro** [algorand/indexer#196]
Hi, I'm getting this log with the latest available build.

`Sep  9 21:34:02 ns576000 algorand-indexer[15642]: 2020/09/09 21:34:02 err handling follow block 5122703, msgpack decode error [pos 503]: no matching struct field found when decoding stream map with key apap`

Will a new release be available soon?

Regards,
Mauro.

**Comment by brianolson** [comment]
2.1.4 is available

**Comment by mxmauro** [comment]
Hi @brianolson thanks. Where is it? I cannot locate it on releases page. Is it not longer here?

**Comment by brianolson** [comment]
What's the URL of the releases page you're looking at? If there's a stale copy we should fix that or make it redirect.

**Comment by mxmauro** [comment]
Here: https://github.com/algorand/indexer/releases

Also https://developer.algorand.org/docs/run-a-node/setup/indexer/#download-the-indexer-binaries points to look in the above url.

**Comment by brianolson** [comment]
Oops, you're right, I was confused. `algod` is at 2.1.4, indexer is at 2.1.1.
Which network are you following? Testnet? So that I can look at the right block 5122703

**Comment by mxmauro** [comment]
Sorry for the delay (was in a call). It was on betanet but started the indexer again but now it is indexing from block ~5110790... ~10k blocks before the original message. Some sort of auto-recovery feature? hahaha.

I'll check when reaches the faulty block and see what happens.

**Comment by mxmauro** [comment]
Now worked fine @brianolson , no clue about why the original syslog message. I'll close this.

Thanks for the assistance.
