### ISSUE TITLE
before-time and after-time filters are slow

### ISSUE THREAD

**Issue by algorotem** [algorand/indexer#202]
When querying for transactions in a specific wide time frame and a and a limit, the query times out. 
Seems like the backend first fetches all transactions and just then tries to limit the results.

suggested solution (by @winder) - map the time range to rounds (which indexed) and run the query on them.

**Comment by brianolson** [comment]
A specific api query url would make this much easier to reproduce and fix

**Comment by anya2go** [comment]
I had an issue running 
```
....
response = myindexer.search_transactions(start_time=2020-08-01T00:00:00+00:00, 
                                                                         end_time=2020-08-08T04:00:00+00:00,
                                                                         next_page=nexttoken)
```
raising the error: ```IndexerHTTPError: {"message": "Endpoint request timed out"}```

I was able to get the full data only by requesting a time frame of 6 hours each time

**Comment by winder** [comment]
This issue could also be described as "time filters are slow".

My proposed solution is for the API layer to convert timestamps to round, and to remove the time filter from the IndexerDB interface.

**Comment by brianolson** [comment]
Will, makes sense, do two queries for round >= start time, round <= end time, then build the actual txn query on rounds.

**Comment by pbennett** [comment]
Out of curiosity, why is this necessary?
The existing query just joins against block_header and the realtime field in block_header is already indexed.
One would think that Postgres should use the timestamp index when appropriate.   Indexed timestamps should be really basic for Postgres to handle.  Is there something about the query that's forcing it to not use it?

I guess worst case, a double fetch wouldn't be the worst to get the bounding block range if that performs better (even though the timestamp is just an int underneath as well).  I'd be curious to look at a query plan from one of these poorly performing queries.

**Comment by purestaketdb** [comment]
Just ran into this today - any schedule for a resolution?

**Comment by winder** [comment]
@purestaketdb My plan is to implement the double fetch solution @pbennett described, but there are a lot of higher priority tasks eating up my time recently.

**Comment by purestaketdb** [comment]
This sprint is in the past, but the ticket isn't closed and I've been struggling with the speed of a related query where the user searches for transactions newer than a specified date. Any update?

**Comment by purestaketdb** [comment]
Closed because....?
