### ISSUE TITLE
Endpoint to get historical ledger supply values

### ISSUE THREAD

**Issue by fabrice102** [algorand/indexer#205]
Is it possible to get historical ledger supply values, i.e., values of https://developer.algorand.org/docs/reference/rest-apis/algod/v2/#get-v2ledgersupply for previous rounds?

Can we add to the above values, a field with the total supply (i.e., 10B Algos on MainNet and TestNet)?

**Comment by algoanne** [comment]
Hi @fabrice102 , I know it's been a while on this one - if still relevant to you, can you explain how this is useful?
