### ISSUE TITLE
'txn type' encoding not consistent 

### ISSUE THREAD

**Issue by anya2go** [algorand/indexer#214]
## Summary
Up until round no. 8734689, the type of transactions saved in UTF-8 encoding.
Starting round no. 8734690 it's saved in base64

Restoring the issue:
1. select distinct(txn -> 'txn' -> 'type') from txn where round between 8734680 and 8734689

	?column?
0	pay
1	axfer

2. select distinct(txn -> 'txn' -> 'type') from txn where round between 8734690 and 8734700

	?column?
0	YXhmZXI=
1	cGF5

3. select distinct(txn -> 'txn' -> 'type') from txn where round between 8734689 and 8734690

	?column?
0	pay
1	YXhmZXI=
2	cGF5
3	axfer

Note: This is only visible by people using postgres directly

## Requirements / Solution
We need to document that this encoding would be different. Where should we document this?

## Urgency
Not super urgent because it's only impacting postgres users and it's not incorrect data. More of a cleanliness fix.

**Comment by brianolson** [comment]
implementation note: in `idb/postgres/postgres.go` just inside `func (db *PostgresIndexerDb) AddTransaction(...)` creating the json with
`jsonbytes := idb.JsonOneLine(txn)`
consistently makes txn.txn -> 'txn' -> 'type' be text and not base64, but e2e test fails in a way that needs further observation.
