### ISSUE TITLE
Historical account information very slow for accounts with many transactions

### ISSUE THREAD

**Issue by fabrice102** [algorand/indexer#217]
This may be hard to avoid, but historical information is very slow to get for accounts with many transactions since the queried round.
For example:

```
curl "https://indexerURL/v2/accounts/5K6J3Z54656IR7YY65WNJT54UW6RBZZYL5LWQUTG4RWOTRTRBE2MR2AODQ?round=8128717"
```
takes more than one minute.

**Comment by brianolson** [comment]
The internal process is to apply transactions in reverse from the present, so yes, that's just always going to take a while if there has been lots of traffic.
