### ISSUE TITLE
[5] Docker container that has algod and indexer

### ISSUE THREAD

**Issue by rotemh** [algorand/indexer#22]
One quick-start docker container with algod and algorand-indexer and postgres

**Comment by onetechnical** [comment]
Need to re-vet this with Rotem. Some of this may already be covered by Will's work with docker-compose, so need to see if this is a real ticket, and what the use cases are.

**Comment by jeapostrophe** [comment]
We at Reach have built this if anyone needs it --- https://github.com/reach-sh/reach-lang/tree/master/scripts/algorand-devnet --- the image doesn't contain postgres, but we use a compose file that connects to postgres. I'm happy to chat with anyone who wants to work on adapting what we have to your uses.

**Comment by winder** [comment]
More related work
https://github.com/algorand/algorand-sdk-testing/
https://github.com/algorand/sandbox/issues/14
