### ISSUE TITLE
Ability to get asset details in bulk

### ISSUE THREAD

**Issue by algodesk-io** [algorand/indexer#231]
await indexer.searchForAssets().index(id).do();

this supports only search asset by asset id. is there a way to get assets details by passing array of asset ids or comma separated asset ids ?

i don't think it is supported yet.

Can we add bulk API support for this ?

**Comment by ian-algorand** [comment]
While we can see your desire to have this additional functionality, it's relatively low on our priority list since you can still achieve the same result by looping. We appreciate your contribution and let us know if it poses a greater problem than what you had originally cited.
