### ISSUE TITLE
HTTP 500 Internal Server Error: failed to retrieve information from the ledger

### ISSUE THREAD

**Issue by fermiks** [algorand/indexer#232]
I have an Algorand node up and running and I am playing with the indexer version 2.1.1. I run it locally in the same computer as the node and experience the following error. I show my console session below: 

(also tried running it with the --no-algod option but the database does not seem to be updating).

./algorand-indexer daemon --algod /var/lib/algorand -P "host=localhost user=postgres password=password dbname=mainnet" --pidfile "/var/lib/algorand/algorand-indexer.pid"
serving on :8980
⇨ http server started on [::]:8980
2020/10/29 23:54:26 catchup block 0, err HTTP 500 Internal Server Error: failed to retrieve information from the ledger
2020/10/29 23:54:26 r=0 err getting block 0, HTTP 500 Internal Server Error: failed to retrieve information from the ledger
2020/10/29 23:54:26 r=1 err getting block 0, HTTP 500 Internal Server Error: failed to retrieve information from the ledger
2020/10/29 23:54:26 r=2 err getting block 0, HTTP 500 Internal Server Error: failed to retrieve information from the ledger

**Comment by winder** [comment]
Is `/var/lib/algorand` a data directory? The `--algod` parameter needs to point to the directory containing `algod.net` and `algod.token`

**Comment by winder** [comment]
Closing old issue. Please re-open if this is still a problem.

**Comment by haammar-ledger** [comment]
I am having the exact same issue:
```
$ export ALGORAND_DATA=/var/lib/algorand
$ ./algorand-indexer daemon -P "host=127.0.0.1 port=5432 user=algorand password=algorand dbname=algorand-mainnet sslmode=disable" --algod=$ALGORAND_DATA
serving on :8980
⇨ http server started on [::]:8980
2021/02/18 18:07:39 catchup block 0, err HTTP 500 Internal Server Error: {"message":"ledger does not have entry 0 (latest 12141243, committed 12141243)"}

2021/02/18 18:07:39 r=0 err getting block 0, HTTP 500 Internal Server Error: {"message":"ledger does not have entry 0 (latest 12141243, committed 12141243)"}

2021/02/18 18:07:39 r=1 err getting block 0, HTTP 500 Internal Server Error: {"message":"ledger does not have entry 0 (latest 12141243, committed 12141243)"}

2021/02/18 18:07:39 r=2 err getting block 0, HTTP 500 Internal Server Error: {"message":"ledger does not have entry 0 (latest 12141243, committed 12141243)"}

2021/02/18 18:07:44 reclient happened
2021/02/18 18:07:44 catchup block 0, err HTTP 500 Internal Server Error: {"message":"ledger does not have entry 0 (latest 12141244, committed 12141244)"}

2021/02/18 18:07:44 r=0 err getting block 0, HTTP 500 Internal Server Error: {"message":"ledger does not have entry 0 (latest 12141244, committed 12141244)"}

2021/02/18 18:07:44 r=1 err getting block 0, HTTP 500 Internal Server Error: {"message":"ledger does not have entry 0 (latest 12141244, committed 12141244)"}

2021/02/18 18:07:44 r=2 err getting block 0, HTTP 500 Internal Server Error: {"message":"ledger does not have entry 0 (latest 12141244, committed 12141244)"}

2021/02/18 18:07:44 failing to fetch from algod for 5.006351899s, (since 2021-02-18 18:07:39.761878972 +0000 UTC m=+0.803485886, now 2021-02-18 18:07:44.768230856 +0000 UTC m=+5.809837785)

```

**Comment by haammar-ledger** [comment]
If I understand correctly, the indexer is requesting block 0 and the node responds it doesn't have info about block 0. It's unexpected as I configured my node as `"Archival": true`.

Something else, after using fast catchup, I notice that anytime I restart the node using `sudo systemctl [stop|start] algorand@$(systemd-escape ${ALGORAND_DATA})`, it restarts synchronization all over from block 0, even though the node was fully sync before I stopped it...

Is fast catchup compatible with archival?...

**Comment by winder** [comment]
@haammar-ledger are you able to run this command? It should get the first round from a node storing things in the `$ALGORAND_DATA` directory.
```
curl -H "Authorization: Bearer $(cat $ALGORAND_DATA/algod.token)" "$(cat $ALGORAND_DATA/algod.net)/v2/blocks/0"
```

**Comment by haammar-ledger** [comment]
Yes, now it works. My issue may have been related to not having space left on the drive where $ALGORAND_DATA was, so I moved it to another drive, and now both the node and the indexer are syncing without errors since a few days.

However I also didn't use fast catchup this time, I'm not sure whether it did or did not cause an issue, maybe I'll try it again on a separate data directory when this sync is over.

**Comment by richardpoole** [comment]
@haammar-ledger I'm experiencing the same issue and I think you're right about it being caused by fast catchup. It would make sense that fast catchup starts at a given block, so blocks prior to the catchpoint aren't sync'ed.
