### ISSUE TITLE
endpoint to broadcast a tx

### ISSUE THREAD

**Issue by roccomuso** [algorand/indexer#237]
Correct me If I'm wrong but I read that v1 endpoints (those exposed from the node) are being deprecated and v2 (indexer) is gonna replace them all.

I'm wondering what's the replacement for the POST `v1/transactions` endpoint to broadcast a raw transaction to the network? Is it possible to broadcast transaction through the indexer? what's the API?

Thanks

**Comment by brianolson** [comment]
Posting transactions should still go through `algod` not indexer.

**Comment by roccomuso** [comment]
so the POST v1/transactions will be kept and working?

**Comment by brianolson** [comment]
POST v1/transactions was only ever `algod` and not indexer

**Comment by algorotem** [comment]
@roccomuso `v1` is deprecated and eventually will not be part of `algod`. If possible, please switch to `v2` at your earliest convenience. The call on `v2` is simply `POST v2/transactions`. 
Also, as mentioned above, posting transactions is part of `algod` and will not (at least for the foreseeable future) be part of indexer. 
Please let me know if there are any other concerns.

**Comment by roccomuso** [comment]
So to be clear I'd be able to broadcast transactions using `POST v2/transactions`. I'm asking because I did not see this on the documentation.

**Comment by algorotem** [comment]
Correct, you're already able to. Here is the link to the [documentation](https://developer.algorand.org/docs/reference/rest-apis/algod/v2/#post-v2transactions)
