### ISSUE TITLE
Feature Request:  Prometheus metrics endpoint

### ISSUE THREAD

**Issue by PSjoe** [algorand/indexer#239]
Would it be possible to add a prometheus metrics endpoint as there is with algod?  This would make monitoring this much more robust.  Some possible candidates:

* How many blocks have been ingested (updater)
* How many transactions have been inserted into the DB
* How many API requests have been serviced
* API request service timing

~In addition, it would be quiet helpful to have a command line flag that would output the specific version of the installed binary.  There doesn't currently seem to be such a flag.~ we have this now

**Comment by brianolson** [comment]
See also #174 for previous discussion of stats to serve.

**Comment by ian-algorand** [comment]
Thanks for the contribution. Would it be possible to give us more details on how you'd be using these metrics or how this might fit into the overall application you're building (or problem you're trying to solve) we can go from there.

**Comment by PSjoe** [comment]
We're working on moving our Indexer-v2 setup to a  Kubernetes setup monitored by Prometheus.  The officially sanctioned way to monitor things there is with a `/metrics` end point of some sort.  Algod has this, but indexer currently does not.

We have one pod dedicated to inserting blocks into PostgreSQL and N number of pods that are read-only.   We're very interested in knowing that a given indexer updater is keeping up.  Right now we parse the logs  of the updater and determine things like:

* how long does it take to ingest a given block
* how many transactions were in a given block

There's not a lot else in the logs most of the time.  We then graph these things out to see how things are performing over time.

While we can still do this in a Kubernetes world, it would be quite convenient to be able to do things like we can do with the algod metrics.  For example, the Prometheus `rate` function against the `algod_ledger_round` tells us if an algod node is keeping up or not.

So by having a count of the blocks ingested by the indexer updater and perhaps the TXs processed, we could determine if our setup is getting slower or faster.  (Perhaps our PostgreSQL instance is coming under more load than we realize, our Updater needs more horsepower, or something else is going on.)

On the reader side, it would be helpful to  see how many API requests have been served, and how long they're taking.  Again, with enough effort, we can calculate these things out of the logs.  But it seems like a metrics endpoint would be ideal.

Perhaps the shorter answer is we'd love to get metrics that help us make sure our indexers are running smoothly and have plenty of headroom. If something does get a bit out of whack, we'd like some clues as to why things started to go off the rails. (Like an onslaught of transactions in each block or spike in latency when inserting blocks/transactions.)  

Hopefully the flag for checking the build number is pretty obvious.  :)

**Comment by winder** [comment]
Additional performance metrics:
- tx-type per block
- processing times:
    - total block handling time
    - block fetching
    - block/tx insert
    - accounting computations
    - accounting DB update
    - perhaps per tx-type timing as well to help figure out the impact of things like:
        - asset closes require updating the transaction
        - asset config requiring querying for the current configuration

One thing I'm not sure of is whether this data should be provided statsd/prometheus style as metric aggregations, or added as structured log messages to be aggregated in whatever granularity is useful. Or both.

**Comment by PSjoe** [comment]
The prometheus endpoint would be highly useful in a Kubernetes world.  For example, even emitting the most recent block number would allow someone to create an alarm that would calculate the rate of that metric and alert if an indexer (configured for updating) has gotten stuck.  

While extracting that data from the logs is also  do-able (and even quite interesting when log aggregation systems are in place), it requires a lot more moving parts.

**Comment by pbennett** [comment]
The algorand node itself already has a prometheus endpoint as well (/metrics), so the indexer not having one is a bit out of place actually.
