### ISSUE TITLE
algod and indexer don't have matching behavior when it comes to "non existing" accounts

### ISSUE THREAD

**Issue by algorotem** [algorand/indexer#275]
When looking up for a "nonexisting" (by nonexisting we refer to an account that never transacted on the blockchain) algod returns the account with 0 balance but the Indexer returns 404. 
There is a need to align the two. Preferably to match indexer to algod. Now when `created-at` is there, it makes it even easier.  

The rationale behind not returning 404 in algod is that all accounts in the space exist, just with a balance of zero. When a user generates a new account, s/he essentially picking one at random from the entire space.  

## Urgency/Relative Priority
Want to do this now because it's a quick win, and if we delay, we risk users getting into bad habits (and exposing them to generally unexpected behavior of the system)

**Comment by brianolson** [comment]
Counterpoint: what the Indexer says has more information. `algod` forgets that an account ever existed after it is closed. `algod` cannot distinguish between 'never existed' and 'is zero right now'. Also, for an HTTP API 404 is more correct than a zero record.

**Comment by algoanne** [comment]
closing as per the comment above.
