### ISSUE TITLE
Enhancement: Add proposer to blocks 

### ISSUE THREAD

**Issue by purestaketdb** [algorand/indexer#277]
## Summary
The only way now to retrieve the proposer of a block is from Algod and in msgpack and encoded. It would be helpful to have it available from the Indexer. 

## Scope/Requirements
The addition of proposer to the data model, a migration script to add it to existing indexers, and adding it to the API.

## Urgency/Relative Priority
It is helpful, but not urgent

**Comment by algoanne** [comment]
Looking at this now - 

We can add the proposer to the block in the indexer. This will require a DB migration to add the column. We can do this.

Backfilling the data requires a more serious migration, requires getting all the historical blocks again. We are not sure we need to do this.

**Comment by gmalouf** [comment]
This is addressed via https://github.com/algorand/indexer/pull/1608
