### ISSUE TITLE
Endpoint timeouts on v2/assets/*/transactions

### ISSUE THREAD

**Issue by curveballdaniel** [algorand/indexer#278]
## Summary
*Describe the problem identified or the general goal of this issue*
Hi,

I’m currently running a fully synced Algorand 2.3.0 mainnet relay node, with a 2.2.1 indexer attached. There are some endpoints I have trouble working with, specifically `v2/assets/*/transactions` alongside its queries listed below. Every call times out, usually taking about 5 or so minutes before doing so. 

I’ve been using asset 5, Joe-Coin, which doesn’t have many transactions (https://algoexplorer.io/asset/5). Yet each call still seems to timeout regardless.

Here’s a list of the current endpoints the indexer is hanging on:
```
// the base endpoint
v2/assets/5/transactions

// and the assorted query + parameters
v2/assets/5/transactions?address=5K6J3Z54656IR7YY65WNJT54UW6RBZZYL5LWQUTG4RWOTRTRBE2MR2AODQ
v2/assets/5/transactions?address=5K6J3Z54656IR7YY65WNJT54UW6RBZZYL5LWQUTG4RWOTRTRBE2MR2AODQ&address-role=sender
v2/assets/5/transactions?address=5K6J3Z54656IR7YY65WNJT54UW6RBZZYL5LWQUTG4RWOTRTRBE2MR2AODQ&address-role=receiver
v2/assets/5/transactions?address=5K6J3Z54656IR7YY65WNJT54UW6RBZZYL5LWQUTG4RWOTRTRBE2MR2AODQ&address-role=freeze-target
v2/assets/5/transactions?after-time=2020-12-01
v2/assets/5/transactions?before-time=2019-12-01
v2/assets/5/transactions?currency-greater-than=1
v2/assets/5/transactions?currency-less-than=100
v2/assets/5/transactions?min-round=700000
v2/assets/5/transactions?next=dQGgAAAAAAAQAAAA
v2/assets/5/transactions?note-prefix=c2hvd2luZyBwcmVmaXg=
v2/assets/5/transactions?rekey-to=true (and false)
v2/assets/5/transactions?sig-type=sig
v2/assets/5/transactions?sig-type=msig
v2/assets/5/transactions?sig-type=lsig
v2/assets/5/transactions?tx-type=pay
v2/assets/5/transactions?tx-type=keyreg
v2/assets/5/transactions?tx-type=acfg
v2/assets/5/transactions?tx-type=axfer
v2/assets/5/transactions?tx-type=afrz
v2/assets/5/transactions?tx-type=appl
```
These `v2/assets/*/transactions` queries below work with no problem.
```
v2/assets/5/transactions?limit=1
v2/assets/5/transactions?txid=TWIWLW25FKBKKY63ZNEWMOJRCYR7HGNBYZTK64QB6S6RJJMYN6LA
v2/assets/5/transactions?round=10000000
v2/assets/5/transactions?max-round=10000000
```
Curl will frequently result in:
```
`curl: (52) Empty reply from server`
```
After a couple minutes, for each non-working call.

## Scope/Requirements
*What's involved in this issue? What's required to achieve the goal?*
Fixing a timeout/obtaining a response from what should be a working endpoint. 

## Urgency/Relative Priority
*How urgent is this issue? What are the timing considerations to take into account?*
Normal priority

**Comment by brianolson** [comment]
Try adding this index to your database
```sql
CREATE INDEX CONCURRENTLY IF NOT EXISTS txn_asset ON txn (asset, round, intra);
```

**Comment by curveballdaniel** [comment]
Hey @brianolson - worked like a charm! Every single failing endpoint above has been fixed. Thanks so much.

The truth is, I've got some other endpoint + query combinations failing (timing out as described above) as well, most spanning under
```
// a bunch of queries here (not all, but most. Base endpoints work fine.)
v2/accounts/*/transactions
v2/transactions

// some one-offs failing here
v2/assets/5/balances?currency-greater-than=1
v2/accounts/*?round=10000000
v2/accounts?auth-addr=<zero-address>
v2/accounts?currency-less-than=100
```

Is there an index fix for these endpoints as well?

Let me know if you'd need exact calls + queries for the timing out calls above.

**Comment by ian-algorand** [comment]
Sounds like this issue has been resolved. Closing for now but feel free to reopen if problems persist.
