### ISSUE TITLE
Feature Request:  Indexer DB validation mode

### ISSUE THREAD

**Issue by PSjoe** [algorand/indexer#282]
## Summary
Currently Indexer can run as an DB updater  or a read-only mode.  It would be helpful if there as a third mode that would validate blocks between algod and what's in the PostgreSQL backend.  Ideally, it would have some REST API or Prometheus endpoint that would produce a list of blocks that have failed validation.

## Urgency/Relative Priority
- Not über urgent, but might help catch latent issues in the DB.  As more apps and wallets rely on the data Indexer is returning from the PostgreSQL backend, it seems it would be more important to verify the accuracy of that data.

**Comment by algorotem** [comment]
Hi @PSjoe,

Thanks for that comment. The idea of a live one is great, though I'm not sure how it "fits" in the current architecture. It seems like it would fit an external service. Maybe we would be able to run a validation after every block simply as part of the import process (though might be tricky performance-wise). Nonetheless, we would look into it.

**Comment by winder** [comment]
@PSjoe we have a couple tools which can validate indexer and algod:
https://github.com/algorand/indexer/tree/develop/cmd/validator
https://github.com/algorand/indexer/blob/develop/misc/validate_accounting.py

It's unlikely that we'll build these into indexer directly.

**Comment by winder** [comment]
Closing since we have the validation tools for this now.
