### ISSUE TITLE
prevention of multiple writers

### ISSUE THREAD

**Issue by brianolson** [algorand/indexer#285]
## Summary
Add things to the Indexer and database to prevent multiple writers. It might not be 100%, but Indexer can exit-with-warning or require a `--force` type option.

## Implementation Ideas
Add a field to the ImportState which is a timestamp of when it is written.
Add another row to metastate that is an app lock claim, probably it would have start-time and process-id. On graceful exit (^C or kill other than -9) that would be cleared.
On startup check that row, if not present, set one. If present, check ImportState last written time, if that's older than about a minute assume the prior task died, otherwise log error ("looks like there's another writer, exiting") and exit

## Urgency/Relative Priority
Some mystery bugs seen in the wild might be because of multiple writers doing inconsistent accounting to the database? This could be a big win to avoid a lot of these bugs (currently it's really easy to mess things up)

**Comment by winder** [comment]
Resolved by #289
