### ISSUE TITLE
Possible invalid "defaultFrozen" after a daemon reset.

### ISSUE THREAD

**Issue by winder** [algorand/indexer#290]
## Summary
In the accounting function `accounting.go::AddTransaction` it appears that we only initialize `accounting.defaultFrozen[assetID]` cache when there is an AssetConfig transaction. This means that after a restart the cached values will be lost and invalid when creating new asset holdings.

## Scope/Requirements
Reproduce the scenario:
1) Create an asset with defaultFrozen = true
2) Create a new asset holding.
3) Verify that the Indexer has marked the asset holding as frozen.
4) Restart Indexer
5) Create a new asset holding.
6) Verify that the Indexer has marked the asset holding as frozen.
7) Fix the bug if there is one.
8) Continue to step 1.

## Urgency/Relative Priority
Isolated data integrity issue.

**Comment by brianolson** [comment]
Looks like I had the code set up to use db.GetDefaultFrozen() to initialize that, and then update it on acfg, but never did that intended initialization step.

**Comment by brianolson** [comment]
The good news is than mainnet currently has _no_ DefaultFrozen=true assets.

**Comment by egieseke** [comment]
It does not require restarting indexer to show the bug, I created an asset in default frozen state, opted into it from another account, and then showed the account info from both algod and indexer, algod shows that it is frozen, but indexer says not. 

$ curl -H "x-algo-api-token: <api-token>" https://node-testnet.aws.algodev.network/v2/accounts/VVQ74GSLGX3X7IZWEUSSXW7VDRHJ4E4YQM36GMKAKHOMZHSOHAJFWJH5PU
{"address":"VVQ74GSLGX3X7IZWEUSSXW7VDRHJ4E4YQM36GMKAKHOMZHSOHAJFWJH5PU","amount":299000,"amount-without-pending-rewards":299000,"apps-local-state":[],"apps-total-schema":{"num-byte-slice":0,"num-uint":0},"assets":[{"amount":0,"asset-id":13795637,"creator":"HZ57J3K46JIJXILONBBZOHX6BKPXEM2VVXNRFSUED6DKFD5ZD24PMJ3MVA","is-frozen":true}],"created-apps":[],"created-assets":[],"pending-rewards":0,"reward-base":25553,"rewards":0,"round":12007121,"status":"Offline"} 

$ curl -H "x-indexer-api-token:<api-token>" https://indexer-testnet.aws.algodev.network/v2/accounts/VVQ74GSLGX3X7IZWEUSSXW7VDRHJ4E4YQM36GMKAKHOMZHSOHAJFWJH5PU
{"account":{"address":"VVQ74GSLGX3X7IZWEUSSXW7VDRHJ4E4YQM36GMKAKHOMZHSOHAJFWJH5PU","amount":299000,"amount-without-pending-rewards":299000,"assets":[{"amount":0,"asset-id":13795637,"creator":"","is-frozen":false}],"pending-rewards":0,"reward-base":25552,"rewards":0,"round":12007245,"sig-type":"sig","status":"Offline"},"current-round":12007245} 

curl -H "x-algo-api-token: <api-token>" https://node-testnet.aws.algodev.network/v2/assets/13795637
{"index":13795637,"params":{"creator":"HZ57J3K46JIJXILONBBZOHX6BKPXEM2VVXNRFSUED6DKFD5ZD24PMJ3MVA","decimals":2,"default-frozen":true,"manager":"HZ57J3K46JIJXILONBBZOHX6BKPXEM2VVXNRFSUED6DKFD5ZD24PMJ3MVA","metadata-hash":"MTZlZmFhMzkyNGE2ZmQ5ZDNhNDgyNDc5OWE0YWM2NWQ=","name":"junebug","reserve":"HZ57J3K46JIJXILONBBZOHX6BKPXEM2VVXNRFSUED6DKFD5ZD24PMJ3MVA","total":1000000,"unit-name":"june","url":"http://www.algorand.com"}} 


curl -H "x-indexer-api-token:<api-token>" https://indexer-testnet.aws.algodev.network/v2/assets/13795637
{"asset":{"index":13795637,"params":{"clawback":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY5HFKQ","creator":"HZ57J3K46JIJXILONBBZOHX6BKPXEM2VVXNRFSUED6DKFD5ZD24PMJ3MVA","decimals":2,"default-frozen":true,"freeze":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY5HFKQ","manager":"HZ57J3K46JIJXILONBBZOHX6BKPXEM2VVXNRFSUED6DKFD5ZD24PMJ3MVA","metadata-hash":"MTZlZmFhMzkyNGE2ZmQ5ZDNhNDgyNDc5OWE0YWM2NWQ=","name":"junebug","reserve":"HZ57J3K46JIJXILONBBZOHX6BKPXEM2VVXNRFSUED6DKFD5ZD24PMJ3MVA","total":1000000,"unit-name":"june","url":"http://www.algorand.com"}},"current-round":12007755}

**Comment by algobolson** [comment]
Has anyone coded the primary fix to this yet? Did I skip that step by writing the fixup migration?

**Comment by brianolson** [comment]
I think the system caching default-frozen is all built, just never initialized. There's even a IndexerDB function to fetch all the default-frozen statuses, it's just not hooked up.

**Comment by brianolson** [comment]
https://github.com/algorand/indexer/blob/develop/idb/postgres/postgres.go#L288
I think this should actually be simplified though to only be a map of the assets that are DefaultFrozen=true since a Go map[]bool returns false for things not there.
