### ISSUE TITLE
Add /blocks search endpoint

### ISSUE THREAD

**Issue by anya2go** [algorand/indexer#291]
**Is your feature request related to a problem? Please describe.**

It would be great to be able to get information on all blocks created between start time and end time

**Describe the solution you'd like**

being able to call `indexer.get_blocks(start time, end time)`

**Comment by brianolson** [comment]
Indexer is a lot more transaction-oriented than block-oriented; would fetching the txns for those blocks do what you want?

**Comment by anya2go** [comment]
I guess my goal in this request is to get `block_info` based on the block time. 
I understand it is more transactions oriented, I was wondering if we could add an API call to mimic querying 'block_header' by time frame

**Comment by brianolson** [comment]
So, the result of something like
`SELECT * FROM block_header WHERE realtime BETWEEN '2021-01-01T00:00:00' AND '2021-01-01T00:05:00';`

**Comment by anya2go** [comment]
exactly

**Comment by winder** [comment]
@anya2go what use case do you have where this would be useful? Like Brian mentioned you can get the content of these blocks with the search option pretty easily. Indexer isn't really meant to be an export tool so I'm not sure this really fits with what indexer is trying to do.

We would need to think about what options should be supported if we added a `/blocks` search endpoint, currently, I think there's just a lookup for a particular round.

**Comment by algoanne** [comment]
Hi @anya2go , I don't know if this is still important to you, but - we're moving in a different direction with indexer, and want to avoid adding one-off requests, especially without clear dapp support use cases. That said, we can separately talk about better supporting you for our internal analytics purposes!
