### ISSUE TITLE
Incorrect balance for the rewards pool

### ISSUE THREAD

**Issue by ori-shem-tov** [algorand/indexer#300]
#### Query the indexer for rewards pool info:
```
curl -X GET "$INDEXER_URL/v2/accounts/737777777777777777777777777777777777777777777777777UFEJ2CI" -H  "accept: application/json" -H  "x-api-key: $INDEXER_TOKEN"
```
Result:
```
{
  "account": {
    "address": "737777777777777777777777777777777777777777777777777UFEJ2CI",
    "amount": 22164062878418,
    "amount-without-pending-rewards": 22164062878418,
    "pending-rewards": 0,
    "reward-base": 168228,
    "rewards": 0,
    "round": 11862854,
    "status": "NotParticipating"
  },
  "current-round": 11862854
}
```
#### Compare with the algod account info:
```
curl -X GET "$ALGOD_URL/v2/accounts/737777777777777777777777777777777777777777777777777UFEJ2CI" -H  "accept: application/json" -H  "x-api-key: $ALGOD_TOKEN"
```
Result:
```
{
  "address": "737777777777777777777777777777777777777777777777777UFEJ2CI",
  "amount": 5406657050445,
  "amount-without-pending-rewards": 5406657050445,
  "apps-local-state": [],
  "apps-total-schema": {
    "num-byte-slice": 0,
    "num-uint": 0
  },
  "assets": [],
  "created-apps": [],
  "created-assets": [],
  "pending-rewards": 0,
  "reward-base": 0,
  "rewards": 0,
  "round": 11862850,
  "status": "Not Participating"
}
```
We get a different amount from each query.
The issue seems to be that the indexer does not decrease the reward pool balance by the distributed rewards.

## Scope/Requirements
*What's involved in this issue? What's required to achieve the goal?*

## Urgency/Relative Priority
*How urgent is this issue? What are the timing considerations to take into account?*

**Comment by brianolson** [comment]
This is known. I think algod counts rewards that have been accrued but Indexer only decrements the rewards account when a txn causes an account to receive rewards.

**Comment by brianolson** [comment]
Indexer's treatment of the RewardsPool account maintains `SELECT sum(microalgos) FROM account;` constant, so I feel pretty good about its accounting.

**Comment by ian-algorand** [comment]
Closing as it's a known issue. Thanks for the contribution!
