### ISSUE TITLE
Bootstrap from gossip protocol

### ISSUE THREAD

**Issue by winder** [algorand/indexer#307]
## Summary
If Indexer were able to speak the gossip protocol it should be possible to bootstrap indexer without requiring an archival node. There is still a problem of where to get the genesis file.

## Scope/Requirements
Indexer already has a fetcher interface currently configured to grab blocks one at a time in order from an archival node. We need an alternative implementation which collects blocks from the gossip protocol.

To make it faster we probably need a smarter algorithm able to download batches of blocks in parallel. If we are going to load blocks out of order the import loop needs to decouple the block loading process and the update process. Additionally the indexer DB would need a way to report missing blocks. It might be worth investigating whether or not something like a BitTorrent algorithm would be better than rolling our own P2P downloader.

## Urgency/Relative Priority
This would greatly reduced the requirements for spinning up a new indexer instance and would plugin to indexer using existing abstractions.

**Comment by brianolson** [comment]
By talking to a local trusted `algod` Indexer outsources the validation of the blocks. Indexer doesn't do any crypto checks. If we want to adopt more pieces of the protocol we should do the work on the `algod` end to modularize the protocol code so that we can use it as a library in Indexer.

**Comment by winder** [comment]
There are other solutions to this problem that we would pursue before this suggestion. Closing.
