### ISSUE TITLE
Indexer can momentarily have different accounting than algod

### ISSUE THREAD

**Issue by brianolson** [algorand/indexer#319]
## Summary
While running misc/validate_accounting.py against a live mainnet algod and indexer, some accounts report as different, but then when re-tested they're the same. Investigate difference in algod and indexer behavior with reporting accounting updates as they happen. Is there an off-by-one issue in reporting what round an account is updated thorugh?

## Scope/Requirements
Test harness idea: Write some script to repeatedly fetch account balance from algod and indexer (~10Hz), send a txn to/from that account, see how both update.

## Urgency/Relative Priority
This should be low priority since indexer seems to at worst be a few seconds behind and then it's fine.

**Comment by winder** [comment]
@brianolson we fixed an off-by-some reporting error with `GetMaxRoundLoaded` and `GetMaxRoundAccounted`, do you think there is anything else to learn with this test harness idea?

**Comment by brianolson** [comment]
Maybe it was just that, disagreement on how far we'd actually gotten. I guess we can punt on this issue until the next major release when we try to validate_accounting.py on mainnet. If it still shows up that accounts are temporarily different on indexer and algod we'd need this kind of investigation.

**Comment by winder** [comment]
Sounds good.

If we do see this again, validation code can do something like this to workaround the momentary differences:
```
algodAccount = getAlgodAccount()
indexerAccount = getIndexerAccount()

attempt = 0;
while algodAccount != indexerAccount {
    // only update indexer, it's the one that might be behind.
    indexerAccount = getIndexerAccount()
    attempt++
    if (attempt > 3) return false
    sleep(2)
}

return algodAccount == indexerAccount
```
