### ISSUE TITLE
AssetHolding is missing the creator

### ISSUE THREAD

**Issue by winder** [algorand/indexer#324]
## Summary
The asset holding objects in algod include the creator. Indexer does not.

## Scope/Requirements
There are a few options:
1. At the REST layer lookup the creator for each asset holding and attach it to the API response
2. Add it to the account_asset table so that there is no lookup.
3. Update the query so that postgres adds it to the results in the backend.

## Urgency/Relative Priority
This would probably be a nice feature to add, but there is a simple workaround. If needed search for the asset by ID instead of the creator.

**Comment by winder** [comment]
I think this is still an issue.

**Comment by hm122** [comment]
It seems like the creator was added to the asset holding, but now it has been removed again? Can someone confirm this? Did not find anything about that in the changelog.

**Comment by winder** [comment]
I believe the creator was removed from the holding object in algod when we uncapped the asset/application limit.
