### ISSUE TITLE
How to return blocks with many transactions

### ISSUE THREAD

**Issue by winder** [algorand/indexer#332]
## Summary
In the future, we expect to see blocks with many thousands of transactions. Returning thousands of transactions is unnecessary overhead for anyone who just wants to get the block header.

## Scope/Requirements
There are a couple approaches:
1) Simply remove the transaction array from the block header, users that want the transactions can use the transactions endpoint. Combined with #327 it is easy to verify that all transactions are accounted for.

2) Conditionally enable the transactions-in-block feature for some deployments which can accept the overhead. With already enable some features with the `--dev-mode` feature, this could be more fine grained now that we have a configuration file.

## Urgency/Relative Priority
It's harder to remove features than add them, so setting the precedent now would be a good idea.

# Acceptance Criteria

1) Add a new `header-only` option to the blocks endpoint which skips the transaction query.
2) When building the block response and querying for transactions, set the transactions limit to the server setting for max number of transactions.
3) If the transactions response contains more transactions than the limit, return an error. Follow the pattern used for the Accounts endpoint, which generates an error if the account has too many assets and/or applications. The error should indicate that the `header-only` flag should be enabled.

**Comment by brianolson** [comment]
At an API level do something like this? 
`GET /v2/blocks/{block number}?header-only=1`
