### ISSUE TITLE
Asset Creation Transaction Endpoint

### ISSUE THREAD

**Issue by barnjamin** [algorand/indexer#352]
I'd like an endpoint to request the transaction that created an Asset. 

Because the configuration fields are character limited, I'm storing a piece of data > 32bytes in the note field of the creation transaction. To get the data starting from asset ID I'm getting an Asset ID => Getting Asset  for created at round => Requesting Transactions for the Asset where the max-round = created at round.

If there is a better way to do that, please let me know. Otherwise something like `/v2/{asset_id}/creation` or `/v2/{asset_id}/transaction?initial=true` or w/e would eliminate the extra http call.

If you'd like me to take a look at submitting a PR I'd be happy to given a hint on where to start.

**Comment by winder** [comment]
@barnjamin I believe you can get the initial transaction with `/v2/assets/{asset_id}/transactions?limit=1&tx-type=acfg`, but we don't seem to have the right indexes to allow it to run quickly

**Comment by brianolson** [comment]
Filtering transactions by asset-id is an optional index that may be enabled on some deployments of Indexer. The above query would be fine on those Indexers.

**Comment by barnjamin** [comment]
Ok, so I can run my own indexer and enable that index and I should be good? 

Is it always sorted oldest=>newest?

Also thanks for the quick reply!

**Comment by winder** [comment]
@barnjamin yes.

When you provide query parameters the transactions are sorted oldest=>newest, when you don't provide any parameters it is newest first.

**Comment by barnjamin** [comment]
fantastic, thank you!
