### ISSUE TITLE
Synchronize Errors Across Indexer Daemons

### ISSUE THREAD

**Issue by winder** [algorand/indexer#357]
## Summary
We should come up with a more robust solution around managing errors that also allows synchronizing errors between writer and reader daemons. Because errors currently only exist in a single process, it's impossible for a writer/reader configuration to share critical write failures/stalls with the API user.

Currently, we have a log file and the health endpoint. The way we share errors with the health endpoint is currently a bit of a hack (`Fetcher` interface implements the `error` interface), some sort of ErrorRegistry would be better. Perhaps `IndexerDb` is that error registry?

## Scope/Requirements
There are a few parts to this:
1) The IndexerDb interface needs a way to set and retrieve record errors, something like UID/timestamp/round?/component/severity/error.
2) Some sort of ErrorRegistry object to make it easy to report errors from different parts of the system.
3) Implement the new interface
4) Glue everything together - especially in the health endpoint which would query for errors.

We should also make sure errors are cleared when things go back to normal this could be a simple `get errors for round = N`.

## Urgency/Relative Priority
This is another one of those productization issues. It's not required for the system to work, but it makes it easier for admins and users to understand whats going on and potentially make it easier to investigate problems.

**Comment by brianolson** [comment]
Could stuff a row into `metastate` table, maybe at key `errors` with some json blob of current import errors. Read-only indexer /health could look at that.

**Comment by winder** [comment]
@brianolson that's a possibility, but I was thinking of an errors table so that we didn't have to remove old errors. Though there's an argument to be made that the log file is the source of truth.

**Comment by brianolson** [comment]
I think logging to db is a recipe for space overruns. I guess I was hoping to solve the smaller problem of communicating from writer-indexer to reader-indexer (serving API requests) the notion of "something's not right" so that message can get out to users.

**Comment by winder** [comment]
Related to #262
