### ISSUE TITLE
Migration to remove auth-addr when it equals the account.

### ISSUE THREAD

**Issue by winder** [algorand/indexer#365]
## Summary
Followup to #337

Now that we will no longer add auth-addr when it equals the sender, we should cleanup accounts which have the extra field.

## Scope/Requirements

Static query migration, something like:
```sql
-- you can see the accounts with:
SELECT encode(addr,'base64'),* FROM account WHERE account_data->>'spend'=encode(addr,'base64')

-- so something like this should fix it:
UPDATE account SET account_data=coalesce(account_data, '{}'::jsonb)-'spend' WHERE account_data->>'spend'=encode(addr,'base64')
```

**Comment by brianolson** [comment]
counterpoint: this might not actually be _needed_ because it can be filtered out at the API layer to have parity with `algod` and the redundant value isn't wrong

**Comment by winder** [comment]
this is obsolete.
