### ISSUE TITLE
Incorrect metadata-hash param returned from v2/assets query. 

### ISSUE THREAD

**Issue by barnjamin** [algorand/indexer#366]
When making a request to the v2/assets endpoint, I get what appears to be an incorrect metadata-hash in the response, apparently copied from a different asset in the payload.

The correct metadata-hash is returned when requesting a specific asset by id `/v2/assets/{asset-id}`
![image](https://user-images.githubusercontent.com/520236/109437885-69912380-79f5-11eb-85ea-6b689c409190.png)

The incorrect metadata-hash is returned when making a request to `/v2/assets?name=RareAF&limit=100` and is identical to (copied from?)  another asset in the same payload. 
![image](https://user-images.githubusercontent.com/520236/109437932-95aca480-79f5-11eb-8fd8-085f043b3f20.png)

There may be more params besides metadata-hash returned in the payload that are copied from a different asset but they happen to be identical in my example.

I don't have a test env setup to check but I did browse the relevant section in the indexer and nothing obvious stuck out.

One thing I did notice is the buffered channel here: https://github.com/algorand/indexer/blob/2fbf02d417eafb0720b431c73e81ce1ca69b7c90/idb/postgres/postgres.go#L2521

Adding a buffer to a channel has almost always bit me with a subtle race bug.  Unlikely to be the cause here but maybe something to look at.

**Comment by brianolson** [comment]
Which network is this on? I don't see it on mainnet.

**Comment by barnjamin** [comment]
It was on TestNet
