### ISSUE TITLE
Fix Flaky mlock Failure in CI

### ISSUE THREAD

**Issue by winder** [algorand/indexer#371]
## Summary
The mule environment seems to be having trouble running the indexer. I've been seeing this issue for a while now, it seems to happen >25% of the time and pretty much always goes away after restarting the job:
```
output from 'go' 'run' 'cmd/e2equeries/main.go' '-pg' 'host=localhost port=5432 dbname=e2e_tests sslmode=disable user=root password=root' '-q':
runtime: mlock of signal stack failed: 12
runtime: increase the mlock limit (ulimit -l) or
runtime: update your kernel to 5.3.15+, 5.4.2+, or 5.5+
fatal error: mlock failed
```

Possibly related to this: https://github.com/golang/go/issues/37436

It suggests two workarounds.

## Scope/Requirements
No more flaky failures!

## Urgency/Relative Priority
It's annoying to babysit builds.

**Comment by onetechnical** [comment]
Both of the workarounds make sense: updated Ubuntu to fix the kernel, and improved handling through golang 1.15. This _should_ work, provided this is the root cause of the issue.

**Comment by onetechnical** [comment]
On a side note: I believe docker containers run with the _host_ kernel, not a custom kernel per container. Bumping the ubuntu image likely would not fix the issue.

**Comment by onetechnical** [comment]
Going to merge this as is. Please re-open this or create a new ticket if it does not fix the problem.
