### ISSUE TITLE
Rewind: Remove or Implement /v2/assets/{asset-id}/balances 'round' query parameter

### ISSUE THREAD

**Issue by winder** [algorand/indexer#374]
## Summary
/v2/assets/{asset-id}/balances have a **round** parameter in the spec which is defined as "Include results for the specified round."

The parameter is currently unused so we should either remove the parameter or implement the feature. Considering that nobody has noticed this parameter, we should probably remove it.

**Comment by nullun** [comment]
I was just about to file a new issue on this round parameter not working correctly! I was hoping to use it to retrieve a snapshot of account balances for a particular historic round. If there's no demand for it I'll look at alternatives, but I think it would be nice to have.

**Comment by jiujiteiro** [comment]
+1 for implementing. I saw the parameter in the spec and was hoping to use as well to pull historical data on ASAs.

**Comment by winder** [comment]
This unimplemented parameter is removed by https://github.com/algorand/indexer/pull/872
