### ISSUE TITLE
updateAccounting() bug

### ISSUE THREAD

**Issue by tolikzinovyev** [algorand/indexer#387]
## Summary
importer/helper.go: updateAccounting(), called after importing a block, gets transactions with a limit of 20000. If the number of transactions exceeds that number, the accounting that is committed will not account for some transactions.

## Scope/Requirements
Ideally we would like to import a block and update accounting in the same db transaction as described in #382. At the very least, we can commit accounting round by round.

## Urgency/Relative Priority
Currently this bug is unlikely since blocks contain way less than 20000 transactions.

**Comment by winder** [comment]
There is no limit on the number of results, `yieldTxnsThread` keeps querying the database until it reaches a query with no results.

**Comment by tolikzinovyev** [comment]
I see, it was counter-intuitive. But it's not done in the same db transaction. I will reference this in #351 then.
