### ISSUE TITLE
Cannot use serializable mode in a hot standby 

### ISSUE THREAD

**Issue by algobarb** [algorand/indexer#391]
## Summary
After the betanet indexer switched live on March 3rd, we started seeing "Serializable Read on hot standby" errors in the all-mobile-blue PostgreSQL logs (about every second):

```
2021-03-05 14:44:44 UTC:192.168.103.224(38268):indexer@betanet_green:[13388]:STATEMENT:  BEGIN ISOLATION LEVEL SERIALIZABLE READ ONLY
2021-03-05 14:44:44 UTC:192.168.103.224(38268):indexer@betanet_green:[13388]:HINT:  You can use REPEATABLE READ instead.
2021-03-05 14:44:44 UTC:192.168.103.224(38268):indexer@betanet_green:[13388]:ERROR:  cannot use serializable mode in a hot standby
```
John created a custom build of develop (cf93e3a) to build/deploy to betanet on March 3rd.
It may have to do with some of the indexer serializable code: https://github.com/algorand/indexer/search?q=serializable

[Cloudwatch Link
](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#logsV2:log-groups/log-group/$252Faws$252Frds$252Fcluster$252Findexer-all-mobile-blue-db$252Fpostgresql/log-events$3Fstart$3D-3600000)
[Datadog Link](https://app.datadoghq.com/logs?agg_m=count&agg_t=count&from_ts=1614880354000&index=%2A&live=false&query=service%3Ards%20host%3A%2Amobile%2A%20%28ERROR%20OR%20FATAL%29%20-%22canceling%3Fstatement%3Fdue%3Fto%3Fuser%3Frequest%22%20-%22terminating%3Fconnection%3Fdue%3Fto%3Fadministrator%3Fcommand%22%20-%22invalid%3Finput%3Fsyntax%22&to_ts=1614881254000&cols=host%2Cservice&stream_sort=desc&messageDisplay=inline)
[Datadog Monitor](https://app.datadoghq.com/monitors/30897994?q=total&from_ts=1614875946000&to_ts=1614881406000&eval_ts=1614881406000)

## Scope/Requirements
* Troubleshoot and resolve the serializable errors
* Check that we no longer see similar betanet errors in the PostgreSQL logs (datadog or CloudWatch in the links above) or create a ticket with next steps.

## Urgency/Relative Priority
Medium - betanet seems to have an issue and is logging/alerting errors.

**Comment by brianolson** [comment]
We could reduce the transaction serialization level if the db is opened read-only

**Comment by winder** [comment]
Looks like this happens during queries as well:
```
 % curl -s -H "X-Indexer-API-Token:${AUTH_TOKEN}" -X GET "https://indexer-testnet-green.internal.aws.algodev.network/v2/accounts/POCE5GIBW74DEDEARWR6NHRTQ67F45CLG5SRGQQDKH37ALEASLDAZFQNME"
{"message":"failed while searching for account: account tx err pq: cannot use serializable mode in a hot standby"}
% curl -s -H "X-Indexer-API-Token:${AUTH_TOKEN}" -X GET "https://indexer-betanet-blue.internal.aws.algodev.network/v2/blocks/1"
{"message":"error while looking up block for round '1': pq: cannot use serializable mode in a hot standby"}
```
