### ISSUE TITLE
AddressRole Filter Doesn't Work As Expected

### ISSUE THREAD

**Issue by winder** [algorand/indexer#425]
## Summary
The filter by FreezeAddress doesn't work properly, it doesn't return the freeze transactions.

## Scope/Requirements
There seem to be two problems:
1) We don't add the FreezeAddress to the txn participation index in `importer.go` / `ImportDecodedBlock`.
2) The query in `postgres.go`/`buildTransactionQuery` searches for `afrz` instead of `fadd`.

A migration is required to reprocess all freeze transactions to add the missing txn_participation rows.

**Comment by ian-algorand** [comment]
This might be a dupe, let's double check

**Comment by winder** [comment]
Duplicate of #442
