### ISSUE TITLE
Remove accounting lock

### ISSUE THREAD

**Issue by tolikzinovyev** [algorand/indexer#438]
## Summary
#432 intends to replace the lock, but the current migrations use it and we don't want to modify the code. As soon as we deprecate them or add a blocking migration, we can remove the mutex.

**Comment by winder** [comment]
I'm not sure we should remove this. In some cases, we really do want to perform something without worrying about accounting changes.

One example is being able to create partially blocking migrations by using the lock.

**Comment by tolikzinovyev** [comment]
Why would a retry mechanism not be sufficient?

**Comment by winder** [comment]
One example would be if you wanted to get the most recent rekey transaction for an account. There would always be a race condition.

**Comment by tolikzinovyev** [comment]
Because it's too slow?

**Comment by winder** [comment]
Regardless of the speed. I suppose in my example retry would still work as long as both queries also updated the account. The race condition would decide whether the migration updating the account retries or the CommitRoundAccounting function retries.

There could be other scenarios where the mutex is useful, and it definitely allows us to write simpler migration code.

**Comment by tolikzinovyev** [comment]
I don't think it helps with simplicity. Same way we can get a serialization error using postgres when committing accounting, we can also get it during a migration. So migrations should retry their transactions.

One problem I see though is when an expensive transaction always fails because accounting is committed too often. I think ideally the database should prioritize transactions that have been failing for awhile, but postgres doesn't implement that.
