### ISSUE TITLE
Add the ability to get lifetime earned rewards for an account

### ISSUE THREAD

**Issue by ian-algorand** [algorand/indexer#439]
## Summary
Currently, if an account sends a close txn at any point, the rewards earned data is lost, which makes for a bad experience in the wallet (and other apps that care about account rewards). We really need a way to get total rewards earned. This a highly requested feature for AW

## Scope/Requirements
Needs to be defined here, but it seems like this is possible using the indexer.
Generally, the requirement would be that the app would make a call with an account address as a param and it would return the total earned rewards.

## Urgency/Relative Priority
As mentioned in the summary, while not something that is breaking functionality in the app, it would resolve a lot of UI issues and weird workaround we have in place to try to counteract this issue. Depending on work involved, I would say medium to high priority.

**Comment by algoanne** [comment]
@ian-algorand any update on urgency for this? This is a big lift and we are focusing on indexer stability at the moment, so a priori we won't get to this in the near future.
