### ISSUE TITLE
Define Block Import Test Scenarios

### ISSUE THREAD

**Issue by winder** [algorand/indexer#449]
Define the different block import performance test scenarios. These will be used to evaluate performance over time.

Some ideas. In the final version the distributions should be created in the form of a generator config file rather than the ratios defined below.

name | tx / block | tx distribution | description
-- | -- | -- | --
Full Block Simple | 5k | pay | Full blocks with simple transactions
Small Simple | 10 | pay | Small blocks, this should let us see how much overhead there is to process a block vs raw transaction processing.
Large Block Simple | 40k | pay | 10x blocks to see how indexer performs when processing larger blocks.
Jumbo Block Simple | 200k | pay | See how much room we have to grow.
Full Block Asset Payment | 5000 | .5 : asset-create .5 : asset-optin .9 : asset-xfer | xfer heavy asset transactions.
Full Block Asset Config | 5000 | .1 : asset-create .1 : asset-optin .8 : asset-config | config heavy asset operations.
Full Block Applications | 5000 | ??? | ???

I've marked this as blocking #476 but technically most of the work in that ticket needs to be done regardless of the scenario definitions.

**Comment by Bhaney44** [comment]
`#Issue 44
#Algorand indexer

#There are two scenarios for block import tests.
#This script is a starting point for defining the logic for the two scenarios.

# Scenario 1 success
if block is imported:
    block_import_test = True

# Scenario 2 failure
if block is not imported:
    block_import_test = False
    read_error
    find_bug
    trouble_shoot
    if fixed:
        run_new_test
    else:
        # 2a failure in docker installation
        check_docker
        # 2b failure in scripting
        check_scripting
`
