### ISSUE TITLE
Support databases behind loadbalancers (2)

### ISSUE THREAD

**Issue by tolikzinovyev** [algorand/indexer#461]
## Summary
We need indexer code to work correctly when used with a replicated database, particularly Amazon Aurora.

## Scope/Requirements
- ~Fix most API endpoints~ #373
- Fix account rewinding (accounting/rewind.go)
- ~Fix accounting for importing blocks (importer/helper.go: updateAccounting()); should be partially fixed by #331, `YieldTxns()` can still return inconsistent results~ will be fixed by https://github.com/algorand/indexer/pull/618
- Fix transaction paging (idb/postgres.go: Transactions()); it is possible that the user gets only some transactions for a round because of the limit, but the next Transactions() call will not return the rest of the transactions for this round

## Urgency/Relative Priority
?

**Comment by Blackglade** [comment]
+1 on this. Having issues with this using Aurora.

**Comment by winder** [comment]
@Blackglade what sort of issues are you seeing?

**Comment by Blackglade** [comment]
@winder Deleted my previous comment. My issues with Aurora were not related to the indexer. Aurora has been working great so far :)

**Comment by winder** [comment]
@Blackglade great! Thanks for the feedback.

**Comment by tsachizehub** [comment]
@tolikzinovyev - could you please break this one into two, and we will size these next week ?

**Comment by tolikzinovyev** [comment]
Closing in favor of #619 and #620.
