### ISSUE TITLE
Indexer 2.2.x -> 2.3.x migration fails with db error during migration 7

### ISSUE THREAD

**Issue by gentrysherrill** [algorand/indexer#466]
## Summary

When upgrading from algorand-indexer 2.2.1 to algorand-indexer 2.3.3, a series of db migrations are required, including a long-running migration to calculate cumulative rewards

This migration (m7) fails consistently, with the following error status exposed via the indexer health endpoint (i.e. https://localhost:8980/health):

`{"data":{"migration-required":false,"migration-status":"error during migration 7 (Compute cumulative account rewards for all accounts.): m7: problem querying accounts: account scan err sql: Scan error on column index 1, name \"microalgos\": converting driver.Value type int64 (\"-10499098000\") to a uint64: invalid syntax"},"db-available":false,"errors":["database error: error during migration 7 (Compute cumulative account rewards for all accounts.): m7: problem querying accounts: account scan err sql: Scan error on column index 1, name \"microalgos\": converting driver.Value type int64 (\"-10499098000\") to a uint64: invalid syntax"],"is-migrating":false,"message":"13469090","round":13469090}`

After restarting the algorand-indexer service, the indexer reads all of the transactions once more; currently there are approximately 200 million, and this takes ~20 - 25 minutes.  Sample of log output:

`Apr 27 16:14:01 algorand-indexer[16233]: {"level":"info","msg":"read 200000000 transactions (pass 1)","time":"2021-04-27T16:14:01Z"}`

It immediately fails with the same uint64 conversion error, however, upon starting to read the accounts:

`Apr 27 16:07:53 gcalgo algorand-indexer[15829]: {"level":"info","msg":"started reading accounts","time":"2021-04-27T16:07:53Z"}
Apr 27 16:07:53 gcalgo algorand-indexer[15829]: {"error":"error during migration 7 (Compute cumulative account rewards for all accounts.): m7: problem querying accounts: account scan err sql: Scan error on column index 1, name \"microalgos\": converting driver.Value type int64 (\"-10499098000\") to a uint64: invalid syntax","level":"error","msg":"Migration failed","time":"2021-04-27T16:07:53Z"}`

## Scope/Requirements

The background migration should be able to complete successfully

## Urgency/Relative Priority

High

**Comment by winder** [comment]
@gentrysherrill is this with testnet or betanet? It is unfortunate, but those networks require a full rebuild.

**Comment by gentrysherrill** [comment]
@winder It's with mainnet actually

I also tried the release of 2.3.4 from a couple days ago, but same result

**Comment by winder** [comment]
After discussing with Gentry, I was unable to find the root cause. My best guess is that at some point multiple Indexer writers could have been deployed but it's difficult to verify that after the fact. The stricter postgres serialization in 2.3.x should prevent this kind of problem in the future. A new deployment and DB re-indexing is needed to fix the data.
