### ISSUE TITLE
Omit expected fetcher error from health output.

### ISSUE THREAD

**Issue by winder** [algorand/indexer#486]
## Summary
Some of the recent refactoring / improvements has negatively impacted the health output.

1) The improved errors output includes errors from fetcher. On startup there is always one expected error "ledger does not have entry _", and it is now displayed briefly before being cleared out after successfully continuing.

~2) We no longer update the round accounted value when there are no transactions, so the health round can become out of date. This is especially visible in a private network with sandbox where most rounds will be empty.~

Example of indexer health displayed when starting sandbox:
```
{
  "data": {
    "migration-required": false,
    "read-only-node": true
  },
  "db-available": true,
  "errors": [
    "fetcher error: HTTP 500 Internal Server Error: {\"message\":\"ledger does not have entry 1 (latest 0, committed 0)\"}\n"
  ],
  "is-migrating": false,
  "message": "0",
  "round": 0
}
```

## Scope/Requirements
1) Suppress the fetcher error.
2) Update the round accounted number even for empty rounds.

## Urgency/Relative Priority
This is pretty visible to users and not very hard to fix. We should probably do it.

**Comment by barnjamin** [comment]
https://github.com/algorand/indexer/issues/483 maybe toss this one on there as well?

**Comment by algojack** [comment]
This is also showing up in our cicd pipeline, and sandbox up commands. Would be nice to get this fixed so we don't waste time trying to troubleshoot it every time something else breaks.
