### ISSUE TITLE
Specify config file as parameter

### ISSUE THREAD

**Issue by Blackglade** [algorand/indexer#491]
## Summary
It would be nice if I were able to specify the config file location in the indexer daemon. Being able to do something like:

`./algorand-indexer daemon -f ~/node/indexer.yml`

Current the only work around is to call the daemon directly from the directory where the config file is located. 

## Urgency/Relative Priority
Medium

**Comment by barnjamin** [comment]
https://github.com/algorand/ind exer/blob/develop/config/config.go#L23 looks like there are a few spots it could be read from

**Comment by Blackglade** [comment]
I'm aware of those options. That is however limiting in functionality as based on the individual developers directory/file structure, those areas may not be a convenient place to put the indexer config file. The ask is to open this up to allow for greater customizability by being able to specify the config file location when the process starts.
