### ISSUE TITLE
Algorand Indexer service stuck on testnet-v1.0 block 13991444 

### ISSUE THREAD

**Issue by ATMackay** [algorand/indexer#506]
## Summary
Algorand Indexer service stuck on testnet-v1.0 block 13991444 "ImportDecodedBlock 13991444: block 13991444, Unknown protocol: https://github.com/algorandfoundation/specs/tree/..."

algorand indexer version: 2.3.2 compiled at 2021-04-12T15:29:30+0000 from git hash f6ba02c907192de90a3af80238d872aef0c75042 (modified)

There are no issues with the testnet-v1.0 node (algod version 2.5.6.stable [rel/stable] (commit #219b78d9)).

## Scope/Requirements
Blocks should import without error.

## Urgency/Relative Priority
Adding support for Algorand to our platform requires the indexer service.

**Comment by brianolson** [comment]
Indexer 2.3.4 is released and includes at least one new protocol; can't see if it includes yours due to the cutoff but I think it's worth trying.
https://releases.algorand.com/

**Comment by ATMackay** [comment]
Thanks, I will install v2.3.4 and re-build.

**Comment by ATMackay** [comment]
Fixed, thanks.
