### ISSUE TITLE
Design for Indexer testing infrastructure

### ISSUE THREAD

**Issue by yaovi-a** [algorand/indexer#508]
## Summary
*Describe the problem identified or the general goal of this issue*
We currently don't have a good approach towards dealing with testing indexer bugs. To complete testing an indexer bug, we have to spin up an instance of mainnet with an archival node. This takes up a significant amount of time, and this is all before we can actually run the test, send out results and then have those results reviewed.  

## Scope/Requirements
*What's involved in this issue? What's required to achieve the goal?*
We need a testing infrastructure around indexer to enable quick access to archival, reduce the amount of time necessary to standup an instance. A design needs to be put together to evaluate the issue and evaluate potential approaches. 
 
## Urgency/Relative Priority
*How urgent is this issue? What are the timing considerations to take into account?*
The urgency around this is high. The longer we wait to address this issue, the longer it will take to test indexer bugs.

**Comment by winder** [comment]
@yaovi-a sandbox creates an algod + indexer environment, and the algorand-sdk-testing environment creates one preloaded with some data.

**Comment by algoanne** [comment]
I agree with @winder 's assessment above: we have what we need tools-wise for indexer testing.
