### ISSUE TITLE
Invalid balance returned by indexer?

### ISSUE THREAD

**Issue by alecalve** [algorand/indexer#532]
## Summary
When querying the balance of [KCCJEKP3RTEO5LKBMJWYY527YVPDZJWCLBEUKDD7QUSJAIMZKDUHLVYIWM](https://algoexplorer.io/address/KCCJEKP3RTEO5LKBMJWYY527YVPDZJWCLBEUKDD7QUSJAIMZKDUHLVYIWM) at round [5210200](https://algoexplorer.io/block/5210200), the indexer returns:

```json
{
  "account": {
    "address": "KCCJEKP3RTEO5LKBMJWYY527YVPDZJWCLBEUKDD7QUSJAIMZKDUHLVYIWM",
    "amount": 1700288709,
    "amount-without-pending-rewards": 1700287009,
    "created-at-round": 1438990,
    "deleted": false,
    "pending-rewards": 1700,
    "reward-base": 173060,
    "rewards": 97909801,
    "round": 5210200,
    "sig-type": "sig",
    "status": "Offline"
  },
  "current-round": 14309859
}
```

According the indexer, the balance of that account is 1700.288709 yet tallying all the changes to its balance yields a different result of 1700.087009

Both my calculations and [algoexplorer.io](algoexplorer.io)'s match and indicate that that account's balance at round 5210200 should be instead 1700.087009

Here's the details of my calculation leading to that balance:
``` 
 block_height |                       tx_hash                        |   change   | new_balance
--------------+------------------------------------------------------+------------+-------------
      1438990 | 66GE4YDDM2KPZB7GKSSJYHXKKYIO6TYHHTCQFFAMVR34O7DLIH5Q |         26 |          26
      1439061 | JOR7CSGO7ICD2WFGXLBKEFWLCNLXAVGZ4J4XKTDKM7ZW2UCV7ESA |   0.000026 |   26.000026
      1439061 | JOR7CSGO7ICD2WFGXLBKEFWLCNLXAVGZ4J4XKTDKM7ZW2UCV7ESA |  -0.000001 |   26.000025
      1439061 | JOR7CSGO7ICD2WFGXLBKEFWLCNLXAVGZ4J4XKTDKM7ZW2UCV7ESA |     -0.001 |   25.999025
      1439251 | B22VDCNODOWGNLOGJRJMVT35I7ZC2OXJBPL7B6PGIYDLL7MPRDFA |   0.000075 |   25.999100
      1439251 | B22VDCNODOWGNLOGJRJMVT35I7ZC2OXJBPL7B6PGIYDLL7MPRDFA |       1169 | 1194.999100
      5210176 | YGXHXRDCN6SNHKW6BTSF3JBIURSAP25IUUNR2BLNWJGKJ5NTIN3A |     97.908 | 1292.907100
      5210176 | YGXHXRDCN6SNHKW6BTSF3JBIURSAP25IUUNR2BLNWJGKJ5NTIN3A | 407.179909 | 1700.087009
```

## Scope/Requirements

Algorand node version: 2.6.0
Algorand indexer version: 2.4.0

Both are fully synced.

## Urgency/Relative Priority

It's not highly urgent for me, but probably is for the project.

**Comment by algobolson** [comment]
See the two different amount values returned
```
"amount": 1700288709,
"amount-without-pending-rewards": 1700287009,
```

**Comment by alecalve** [comment]
Ah, I see I had the blinders on. Thanks for the comment!
