### ISSUE TITLE
Missing account in indexer database

### ISSUE THREAD

**Issue by alecalve** [algorand/indexer#533]
## Summary
Querying my indexer for [347MBNZ2JAJR2MGF6MUQZWWZO3HJSZCVEBF7IA2FOAQD7IK6NCLMI5BN3I](https://algoexplorer.io/address/347MBNZ2JAJR2MGF6MUQZWWZO3HJSZCVEBF7IA2FOAQD7IK6NCLMI5BN3I) at round 7,000,000 yields a 404:
```json
{
  "message": "no accounts found for address: 347MBNZ2JAJR2MGF6MUQZWWZO3HJSZCVEBF7IA2FOAQD7IK6NCLMI5BN3I"
}
```

Yet that account definitely had some balance at that round.

Health output:
```json
{
  "data": {
    "migration-required": false,
    "migration-status": "Migrations Complete"
  },
  "db-available": true,
  "is-migrating": false,
  "message": "14310247",
  "round": 14310247
}
```

## Scope/Requirements
Algorand node version: 2.6.0
Algorand indexer version: 2.4.0

Both are fully synced.

## Urgency/Relative Priority
It's not highly urgent for me, but probably is for the project.

**Comment by winder** [comment]
Looks like this is no longer an issue:
```
curl -H "X-Indexer-API-Token:$AUTH_TOKEN" "https://indexer-mainnet.internal.aws.algodev.network/v2/accounts/347MBNZ2JAJR2MGF6MUQZWWZO3HJSZCVEBF7IA2FOAQD7IK6NCLMI5BN3I?pretty"
```
