### ISSUE TITLE
Error when querying deleted app from the api

### ISSUE THREAD

**Issue by anya2go** [algorand/indexer#543]
When looking up a deleted app through the API, not returning anything informative.
On python returns: `HTTPError: {current round: <round number>}`
with curl returns: `{current round: <round number>}`

for example: 
`curl "localhost:8980/v2/applications/238940466"`

**Comment by winder** [comment]
Try `curl "localhost:8980/v2/applications/238940466?include-all=true"`

**Comment by yaovi-a** [comment]
@anya2go Did Will's comment help. If so, we'll close.
