### ISSUE TITLE
Indexer RDS Error: Terminating connection due to idle-in-transaction timeout

### ISSUE THREAD

**Issue by algobarb** [algorand/indexer#551]
## Summary
This error has started appearing more and more frequently since June 1, 2021. This error may be an open session or something. We got 5 alerts with the same FATAL message in 272 log messaged within the past day and have been happening more frequently. 

```
UTC:192.168.92.101(42918):indexer@mainnet_green:[22286]:FATAL:  terminating connection due to idle-in-transaction timeout
19:38:59 UTC | indexer-all-internal-cyan-db
2021-06-24 19:38:59 UTC:192.168.52.132(44810):indexer@mainnet_green:[14233]:FATAL:  terminating connection due to idle-in-transaction timeout
```
RDS errors can be viewed on Datadog: https://app.datadoghq.com/logs?query=%22FATAL%3A%20%20terminating%20connection%20due%20to%20idle-in-transaction%20timeout%22&cols=host%2Cservice&index=&messageDisplay=inline&stream_sort=desc&from_ts=1624478287343&to_ts=1624564687343&live=true
And more logs around that time can be viewed in AWS: https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#logsV2:log-groups/log-group/$252Faws$252Frds$252Fcluster$252Findexer-all-internal-cyan-db$252Fpostgresql/log-events$3FfilterPattern$3D$2522terminating+connection+due+to+idle-in-transaction+timeout$2522$26start$3D-43200000

## Scope/Requirements
* Determine what might be the root cause

## Urgency/Relative Priority
*Medium - I think this may be related to some of the dashboard issues I've seen (we are now setting it to automatically restart at a very frequent interval). It's making our alerts noisy, so it would be good to figure out if this is an actual issue or not.

**Comment by yaovi-a** [comment]
Dup of #385

**Comment by gmalouf** [comment]
I don't believe this is a dupe - logs look like they are referring to RDS connections rather than http ones maintained by the Indexer http server.

**Comment by algobarb** [comment]
Haven't seen this error in the last month in Datadog or Cloudwatch logs. No longer an issue.
