### ISSUE TITLE
Health round does not increase when blocks are empty

### ISSUE THREAD

**Issue by fabrice102** [algorand/indexer#555]
## Summary

If blocks do not contain transactions, round/message in `/v2/health` is not increased.

## How to reproduce

Run the sandbox and do:

```bash
$ curl "localhost:8980/health"
{"data":{"migration-required":false,"migration-status":"Migrations Complete"},"db-available":true,"is-migrating":false,"message":"37","round":37}
```

(here I only made a single transaction at round 37, and no transactions after; despite the fact we're many rounds later, the indexer is stuck at round 37.)

## Urgency/Relative Priority

Minor

**Comment by tolikzinovyev** [comment]
Thanks. It's a known issue and it's being worked on.

**Comment by tolikzinovyev** [comment]
Fixed in develop branch.
