### ISSUE TITLE
Indexer version of GET /v2/status/wait-for-block-after/{round}

### ISSUE THREAD

**Issue by jeapostrophe** [algorand/indexer#562]
It would be nice to be able to wait until the indexer has gotten to a round like `algod` does. This way I don't have to poll and can lower the pressure on the indexer by not sending requests that we know will fail.

**Comment by algoanne** [comment]
Thanks for the suggestion. While this might indeed be nice, it is also a potential attack vector. We want to avoid queries that potentially last a long time (which can cause more load on the server, actually).
