### ISSUE TITLE
Search Transactions by Signature Type with Limit

### ISSUE THREAD

**Issue by iten-alg** [algorand/indexer#563]
## Summary
Py-algorand does not seem to let you search through transactions for specific sig-type and limit (at the same time). Instead, I just get a "Remote end closed connection without response." Not sure if this is an issue on the sdk side or the indexer side.

## Details
Via python sdk:
response = myindexer.search_transactions(sig_type="lsig", limit=1) terminates eventually with "Remote end closed connection without response"

Via curl:
Curl appears to work fine actually, so perhaps it is just an SDK issue, but I figured I should let people know here just in case.

## Urgency/Relative Priority
Presumably low urgency, but this is not my area.

//My apologies if I just did something dumb, and please let me know if you would like any more info

**Comment by winder** [comment]
This is a general performance issue. New versions of Indexer give a much more useful 503 / timeout response.
