### ISSUE TITLE
Getting Transaction Count Estimate by Address

### ISSUE THREAD

**Issue by Blackglade** [algorand/indexer#564]
## Summary
Looking for an optimal way to query total transaction data total by address? The following query results in issues for esspecially popular addresses with >1 million rows. Is there anyway to optimize this:

```sql
SELECT COUNT(*) FROM txn_participation WHERE addr = decode('somehexvalue', 'hex');
```

My query client times out after 45 seconds and this query is unable to complete. Is there anyway to improve the performance here? Even just an estimate would be enough. The other issue is when I do:

```sql
SELECT COUNT(*) FROM txn_participation WHERE addr = decode('somehexvalue', 'hex') LIMIT 100;
```

It still takes 45 seconds. Not sure what is going on o why searching on this table is soo slow.

## Urgency/Relative Priority
Medium

**Comment by Blackglade** [comment]
Here is an example of a query.

```sql
mainnet=> EXPLAIN ANALYZE SELECT COUNT(1) FROM txn_participation WHERE addr = decode('f68ac4a97a08e58b48bb8e319382e0e9d02877ed2e456b359cca438956e6f2fb', 'hex');
                                                                           QUERY PLAN                                                                           
----------------------------------------------------------------------------------------------------------------------------------------------------------------
 Finalize Aggregate  (cost=7564114.37..7564114.38 rows=1 width=8) (actual time=91754.929..91758.266 rows=1 loops=1)
   ->  Gather  (cost=7564114.15..7564114.36 rows=2 width=8) (actual time=91749.074..91758.256 rows=3 loops=1)
         Workers Planned: 2
         Workers Launched: 2
         ->  Partial Aggregate  (cost=7563114.15..7563114.16 rows=1 width=8) (actual time=91749.049..91749.050 rows=1 loops=3)
               ->  Parallel Seq Scan on txn_participation  (cost=0.00..7524692.01 rows=15368856 width=0) (actual time=925.237..89588.666 rows=12309987 loops=3)
                     Filter: (addr = '\xf68ac4a97a08e58b48bb8e319382e0e9d02877ed2e456b359cca438956e6f2fb'::bytea)
                     Rows Removed by Filter: 149326269
 Planning time: 4.495 ms
 Execution time: 91758.321 ms
(10 rows)
```

**Comment by brianolson** [comment]
I think the `LIMIT` form might be sneaking in under the LIMIT because it 'only returns one row' (the aggregate count).
```sql
SELECT COUNT(*) FROM (SELECT * FROM txn_participation WHERE addr = '\x0000395dd0f91ec8d407d0343bb2a752a7a1ba3abe65447fc979460fd57c7df4' LIMIT 100) x;
```

**Comment by brianolson** [comment]
If your running these queries from a script you might be able to to workaround Postgres getting slow by paging the query and adding up the result in your script
```sql
SELECT count(*) FROM txn_participation WHERE addr = '\x0000395dd0f91ec8d407d0343bb2a752a7a1ba3abe65447fc979460fd57c7df4' AND round >= 10000000 AND round < 11000000;
```

**Comment by Blackglade** [comment]
Aghh yup I didn't realize I was using the LIMIT option incorrectly (thanks for the check). Dividing up the work even in a script still causes issues, notably with addresses who have > 25 million transactions. Not sure if there is a way to resolve this allowing better search-ability for aggregate transaction data.

**Comment by Blackglade** [comment]
Closing this out. I've managed to resolve this.
