### ISSUE TITLE
Problems with round update

### ISSUE THREAD

**Issue by Lumene98** [algorand/indexer#565]
## Summary
Hello, we had an indexer implemented for more than a month and for some time we didn't use it, yesterday while trying to implement a script we realized that the indexer wasn't catching up with the testnet:

```
{
  data: {
    'migration-required': false,
    'migration-status': 'Migrations Complete'
  },
  'db-available': true,
  'is-migrating': false,
  message: '7467140',
  round: 7467140
}
```

## Scope/Requirements
The indexer must have had something but we cannot find any problems with it apart from it not being catched up with other indexers(we tested both with purestake and algoexplorer) 

## Urgency/Relative Priority
Could be urgent depending if the issue is global or simply on our side

**Comment by chaihoang** [comment]
Can you redirect this question to the forum?
