### ISSUE TITLE
Indexer returning accounts with removed asset on search

### ISSUE THREAD

**Issue by TheWolfWhoSaidWoof** [algorand/indexer#590]
**The Problem**
When searching for accounts that have an asset enabled but no currency I retrieved accounts that did have the asset but had later removed it.

**Example**
https://algoexplorerapi.io/idx2/v2/accounts?asset-id=285287488&currency-less-than=1
The account 
Z6TUX4NODWWLKFERMSSTEANEHS2PVFC2TJ6CYQQNHLPMHT4WVSVAWUA6OU 
no longer has the asset but is returned
I'll leave this account without the asset so this is reproducible

### Acceptance criteria 
Document changes to reflect expected behavior when include-all=true, and false

**Comment by TheWolfWhoSaidWoof** [comment]
related: If this is meant to not return the asset then isn't the "deleted false" in the elements of the 'assets' array redundant. In other words, it isn't needed in the logical model.

**Comment by TheWolfWhoSaidWoof** [comment]
Forget the comment about deleted. I just found include-all=true which gives it purpose. This does complicate what is expected behavior of this query? if that was set true the query make would expect to find deleted assets

**Comment by winder** [comment]
Thanks for the report, this appears to be a bug.

For the `v2/accounts` endpoint we must only check whether or not the account has been deleted, but if an asset-id filter is being done we also need to check if the asset holding has been deleted.
