### ISSUE TITLE
Can't Search for Testnet Lsigs

### ISSUE THREAD

**Issue by iten-alg** [algorand/indexer#606]
*I wrote an earlier issue, that had some incorrect info, so I am rewriting now that I've identified the correct issue

Attempting to access /v2/transactions?sig-type=lsig does not work on testnet indexer, but does work on mainnet

 curl -H "X-Indexer-API-Token:{token}" "https://indexer-testnet.internal.aws.algodev.network/v2/transactions?sig-type=sig" correctly gives a bunch of normal signature testnet transactions

BUT curl -H "X-Indexer-API-Token:{token}" "https://indexer-testnet.internal.aws.algodev.network/v2/transactions?sig-type=lsig"
gives curl: (56) Unexpected EOF after a delay

Similarly, doing this on the indexer provided by AlgoExplorer https://algoexplorerapi.io/idx2/v2/transactions?sig-type=lsig results in an undocumented error after a delay

Interestingly, the mainnet indexer https://algoexplorerapi.io/idx2/v2/transactions?sig-type=lsig works perfectly fine as far as I can tell both on algoexplorer and internal indexer

**Comment by tsachizehub** [comment]
@winder could you please close this one and link it to the other issue ?

**Comment by winder** [comment]
Related to #385 closing this one.
