### ISSUE TITLE
Add current block number to Indexer-Updater prometheus metrics

### ISSUE THREAD

**Issue by PSjoe** [algorand/indexer#613]
## Problem

Please consider adding the last ingested block number to the prometheus metrics output, analogous to the algod metric "algod_ledger_round".  Having this would allow users to easily compare the current status of indexer vs the current round of the algod source and determine if the indexer is lagging and by how much.  This might prompt a user to look at  things such as if the database requires attention.

## Solution

Export a new metric, perhaps like `indexer_daemon_last_imported_block`.

## Dependencies

None

## Urgency

Not urgent, but would be helpful for monitoring the stack.

**Comment by tolikzinovyev** [comment]
I believe we already implemented this in 5e963edf379afed8aaae2638e30c2da883a8f224, but it hasn't been released.

**Comment by winder** [comment]
@PSjoe thanks for the suggestion Joe, it's coming!
