### ISSUE TITLE
backend: rewind Application state

### ISSUE THREAD

**Issue by algobolson** [algorand/indexer#62]
Given data from #61  implement 'rewind' state-at-round functionality.
Local state rewind for an account works with just the txns on that account.
Global state rewind for an app fetches all txns on the appid.
Fuzed global+local rewind does global state rewind but _also_ filters all those txns into doing rewind on an account's local state.

**Comment by tsachizehub** [comment]
isn't this one already done ?

**Comment by winder** [comment]
> isn't this one already done ?

No

**Comment by yaovi-a** [comment]
Would this be a feature add to the indexer?

**Comment by winder** [comment]
@yaovi-a yes, the idea is that the indexer would return the application state at a particular round. It could enable useful features like replaying app calls after the fact by fetching the before state then re-executing the app call in a simulated environment.
