### ISSUE TITLE
AssetParams omit empty struct tag

### ISSUE THREAD

**Issue by barnjamin** [algorand/indexer#682]
A request to the `transactions` endpoint for an acfg transaction includes asset params.  I expect that it should include only the asset params that were modified in the transaction.

This example shows in the second transaction some of the fields are present and I don't believe they should be:
https://algoexplorerapi.io/idx2/v2/transactions?asset-id=340692285&tx-type=acfg

In this struct, the total and decimals are both missing the `omitempty` struct tag and I think it should be there but I'm positive so not submitting a PR

https://github.com/algorand/indexer/blob/1d9aebbc27bd087dd0d96ac4cb2d842c6c5b2afa/api/generated/v2/types.go#L251-L297

Since the manager/reserve/creator were not modified, I'm not sure they should be included either?

**Comment by winder** [comment]
This is by design. Leaving one of the manager/reserve/freeze/clawback fields blank is how you unset them.
