### ISSUE TITLE
Indexer import performance: Revisit the initial assessment

### ISSUE THREAD

**Issue by yaovi-a** [algorand/indexer#722]
## Problem

We need to identify and create a list of things that we can try to improve indexer import performance. 

## Solution

A to do list of prototype improvements with an estimation of how much we can improve the indexer's import performance.

**Comment by winder** [comment]
We have assessed and implemented many import performance improvements since creating this ticket. There are several more issues in the backlog to improve monitoring to alert us when import performance becomes an issue again.
