### ISSUE TITLE
Indexer: accounting bug

### ISSUE THREAD

**Issue by yaovi-a** [algorand/indexer#725]
### Subject of the issue

The indexer currently runs into an accounting bug when syncing with algod. There's some discrepancy in the transaction that needs to be properly imported by indexer. 
 
### Steps to reproduce

1. Run indexer 2.7.1 full catchup

**Comment by tolikzinovyev** [comment]
Using a variant of binary search, we found that https://github.com/algorand/indexer/commit/a40b36187e413df8f4d537b40c4402a9526adddb fixed the issue.

That commit removes zeroing out of `TotalAppSchema` and `TotalExtraAppPages` fields in `AccountData` which are used by the `min_balance` opcode. My import validation tool found the first accounting discrepancy at round 15821574 (testnet). It contains an application call whose code does use the `min_balance` opcode, which explains the bug.
