### ISSUE TITLE
Properly encode / decode log messages in postgres

### ISSUE THREAD

**Issue by onetechnical** [algorand/indexer#740]
### Subject of the issue

This is a followup to #735 to properly fix this issue. We issued a hotfix in v2.6.4 to just strip non-UTF-8 characters, but would like to handle this properly in the main line. We should ensure that when storing we properly store base64 encoded data in postgres, which will avoid this issue in the future.

Notes from Pavel:

Why base64 and not logsOverride [][]byte in internal/types.go?
REST already returns base64 encoded, it is just a storage issue. Cast to []byte and let postgres to store it as it wants
and remove conversion string -> []byte from rest since it would be already []byte

Included in this should be tests.

### Your environment

N/A

### Steps to reproduce

1. Instantiate a sandbox indexer off of the develop branch
2. Create a transaction using the log opcode with null chars
3. Observe indexer falling over

### Expected behaviour

Indexer able to properly store and return blocks.

### Actual behaviour

Indexer crashes on import.

**Comment by jasonpaulos** [comment]
Note this will require some sort of rebuild or migration to correct the null-stripped incorrect log values currently being stored in the db.
