### ISSUE TITLE
API producing incorrect results

### ISSUE THREAD

**Issue by barnjamin** [algorand/indexer#762]
### Subject of the issue

When requesting transactions containing a specific `application-id` the results returned don't match what a client side filtered query for `appl` calls returns.

### Your environment

Sandbox with dev or release configuration same behavior on develop, master branch at 2.7.1, Tolik's branch

Works as expected on indexer 2.6.4

### Steps to reproduce
Including bash script below to reproduce.

The indexer may return a lower number on client side filtering initially from unimported last blocks (developer mode).

The utility `jq` may need to be installed to get the returned json filtered

```sh

#!/bin/bash

sb="./sandbox"
goal="$sb goal"


cat << EOF > approval.teal
#pragma version 5
txn ApplicationID
int 0
==
bnz main_l4
txn OnCompletion
int NoOp
==
bnz main_l3
err
main_l3:
int 1
return
main_l4:
int 1
return
EOF

cat << EOF > clear.teal
#pragma version 5
int 1
return
EOF


$sb copyTo approval.teal
$sb copyTo clear.teal


accts=(`$goal account list | awk '{print $2}'`)

echo "Creating app"

app_id=`$goal app create --creator ${accts[0]} \
    --approval-prog approval.teal \
    --clear-prog clear.teal \
    --global-byteslices 1 \
    --global-ints 2 \
    --local-byteslices 0 \
    --local-ints 0 | grep 'Created app' |awk '{print $6}' | tr -d '\r'`

app_addr=`$goal app info --app-id $app_id | grep 'Application account' | awk '{print $3}' | tr -d '\r' `

echo "App ID: $app_id"
echo "App Address: $app_addr"

echo "Seeding application addresss"
$goal clerk send -f ${accts[0]} -t $app_addr -a 5000000


n=5
echo "Calling app $n times"
for _ in 1 2 3 4 5
do
    $goal app call --app-id $app_id -f ${accts[0]}
done


echo "Querying..."

client_filter=`curl -s "localhost:8980/v2/transactions?tx-type=appl" | jq "[.transactions[] | select(.\"application-transaction\".\"application-id\"==$app_id)] |length"`
echo "ClientSide filtering, Should return $n: $client_filter"

indexer_filter=`curl -s "localhost:8980/v2/transactions?application-id=$app_id" | jq '.transactions | length'`
echo "Indexer filter, Should be $n (+1 for create?): $indexer_filter"
```

### Expected behaviour
Matching results

### Actual behaviour
No Match

**Comment by winder** [comment]
This is expected behavior. What you're seeing in the "client filter" number, is that the "create" transaction doesn't set `application-id`. This is intentional and relates to the fact that when you create things the ID is unknown. Refer to the `created-application-index` to verify that this txn does indeed relate to the application you're searching for:

```
    {
      "application-transaction": {
...
        "application-id": 0,
...
      "created-application-index": 1,
...
      "tx-type": "appl"
    }
```
