### ISSUE TITLE
Delete `txnbytes` column

### ISSUE THREAD

**Issue by tolikzinovyev** [algorand/indexer#767]
### Subject of the issue

The `txn` table has two columns in addition to others: `txnbytes` and `txn`. The first encodes a transaction in msgpack and the second one in json. We need json encoding to be able to construct sql queries that access individual transaction fields. Presumably, msgpack encoding was added to reduce the risk of encoding / decoding issues for accounting, since import used to be done in two phases: 1) write transactions to the database, 2) read transactions and do accounting.

We now do import in one phase, so this concern is not applicable. To improve import performance, reduce the size of the database, and simplify the code, we should delete the msgpack encoding.

**Comment by gmalouf** [comment]
@tolikzinovyev - have you run any performance tests to demonstrate potential scope of impact here? 

@winder you might be in a better position to speak to the presence of msgpack encoding here...Tolik's reasoning makes sense logically.

**Comment by tolikzinovyev** [comment]
> @tolikzinovyev - have you run any performance tests to demonstrate potential scope of impact here?
> 
> @winder you might be in a better position to speak to the presence of msgpack encoding here...Tolik's reasoning makes sense logically.

I didn't run performance tests, but the fact that we will save disk space and simplify the code is already enough of a reason I think.

**Comment by winder** [comment]
I don't think we need to push ourselves to get this into the next release because the migration to support it later is trivial.

It would be a nice addition though and save a lot of space in the DB.

**Comment by tolikzinovyev** [comment]
> I don't think we need to push ourselves to get this into the next release because the migration to support it later is trivial.
> 
> It would be a nice addition though and save a lot of space in the DB.

I thought so too, but such a migration would be very computationally expensive, will take a long time to run, and will have impact on import and query performance. So I think it's better to do before release.
