### ISSUE TITLE
Add application call accounts to `txn_participation` table

### ISSUE THREAD

**Issue by tolikzinovyev** [algorand/indexer#768]
### Subject of the issue

We currently add the following to the `txn_participation` table: sender, receiver, close address, asset sender, asset receiver, asset close address, freeze account. However, we are missing `Transaction.ApplicationCallTxnFields.Accounts` which are the accounts referenced in an application call. In the future, we might want to construct queries that need this information (e.g., get app call transactions that reference a particular address).

**Comment by gmalouf** [comment]
@winder I remember us discussing storing inner transactions at the same level as outer ones to facilitate searches (with appropriate ref txids, table separation, etc). Did that work ever end up finishing or was it paused?

**Comment by winder** [comment]
> @winder I remember us discussing storing inner transactions at the same level as outer ones to facilitate searches (with appropriate ref txids, table separation, etc). Did that work ever end up finishing or was it paused?

@gmalouf Yes, that work was finished. It's not really related to this issue though.
