### ISSUE TITLE
Indexer v2.8.0 full catchup & Validation

### ISSUE THREAD

**Issue by yaovi-a** [algorand/indexer#774]
Run full catchup with v2.8.0 full catchup 

- [x] Betanet 
- [ ] TestNet & MainNet

### Acceptance criteria 
- Document the resources used in to catchup, the duration of the full catchup and create a story for any failure that occurs.  
- Capture data validation script outcome. Report in slack indexer channel. 
- If there's a failure, create a story capturing the failure/error and add it as a blocker to this story.

**Note:** 
Testing is currently blocked by the followings:

Optional: https://github.com/algorand/indexer/pull/771
Mandatory: https://github.com/algorand/indexer/pull/777.

**Comment by onetechnical** [comment]
We are running three instances:

- algod 3.0.1 - betanet/testnet/mainnet indexer v2.8.0-rc1 catchup w/ postgres 11 on 4x local NVMe (i3.8xlarge)
- algod 3.0.1 - betanet/testnet/mainnet indexer v2.8.0-rc1 catchup w/ postgres 12 on 2x local NVMe (i3.4xlarge)
- algod 3.0.1 - betanet/testnet/mainnet indexer v2.8.0-rc1 catchup w/ postgres 13 on 4x local NVMe (i3.8xlarge)

These were started 11/9 in the evening at various times, but as of 11/10 11:34am this is where they are (in above order):

```
{"data":{"migration-required":false,"migration-status":"Migrations Complete"},"db-available":true,"is-migrating":false,"message":"5390118","round":5390118,"version":"2.8.0-rc1"}
{"data":{"migration-required":false,"migration-status":"Migrations Complete"},"db-available":true,"is-migrating":false,"message":"1722834","round":1722834,"version":"2.8.0-rc1"}
{"data":{"migration-required":false,"migration-status":"Migrations Complete"},"db-available":true,"is-migrating":false,"message":"5070504","round":5070504,"version":"2.8.0-rc1"}
```

```
{"data":{"migration-required":false},"db-available":true,"is-migrating":false,"message":"4139516","round":4139516,"version":"2.8.0-rc1"}
{"data":{"migration-required":false},"db-available":true,"is-migrating":false,"message":"2237074","round":2237074,"version":"2.8.0-rc1"}
{"data":{"migration-required":false},"db-available":true,"is-migrating":false,"message":"4102360","round":4102360,"version":"2.8.0-rc1"}
```

```
{"data":{"migration-required":false},"db-available":true,"is-migrating":false,"message":"5927727","round":5927727,"version":"2.8.0-rc1"}
{"data":{"migration-required":false},"db-available":true,"is-migrating":false,"message":"2709747","round":2709747,"version":"2.8.0-rc1"}
{"data":{"migration-required":false},"db-available":true,"is-migrating":false,"message":"5906032","round":5906032,"version":"2.8.0-rc1"}
```
