### ISSUE TITLE
hook indexer tests with Travis 

### ISSUE THREAD

**Issue by rotemh** [algorand/indexer#78]
build:
`make`

test:
`go test ./...`

integration test:
setup postgres with local admin account.
setup AWS credentials
`python3 misc/e2etest.py`

release:
```Python
python3 -m venv ve3
ve3/bin/pip install markdown2
ve3/bin/python misc/release.py
```

**Comment by btoll** [comment]
This was part of this PR: https://github.com/algorand/indexer/pull/121
