### ISSUE TITLE
v2/assets/assetid/balances does not work with round

### ISSUE THREAD

**Issue by scholtz** [algorand/indexer#787]
### Subject of the issue

I want to list specific owners of asa at specific round.

https://testnet.algoexplorerapi.io/idx2/v2/assets/44526812/balances?round=17866412

It seems that round parameter is not considered in the query.

Documentation says: Include results for the specified round. 

This is not true.

Tested also on mainnet https://algoexplorerapi.io/idx2/v2/assets/384303832/balances?round=17279644

### Your environment

Indexer v 2.3.1

### Steps to reproduce

1. Go to https://testnet.algoexplorerapi.io/idx2/v2/assets/44526812/balances?round=17866412

### Expected behaviour
I do not want to see lines of accounts who optedin after round 17866412

Please either remove round parameter or make it work.

### Actual behaviour

I see more information than it should show.

**Comment by algoanne** [comment]
please see #374. The round parameter is not implemented for this endpoint, we will likely be removing it.

**Comment by scholtz** [comment]
i really need to know the balances of the account at specific round

@algoanne  what is your suggestion how to do it?

**Comment by scholtz** [comment]
@algoanne .. you mean you are going to fix the issue with rewinding? https://forum.algorand.org/t/rewinding-past-txn-type-appl-is-not-currently-supported/5930/3

https://github.com/algorand/indexer/issues/384#issue-826652795

**Comment by algoanne** [comment]
no, currently app txns are not supported by rewind.

if you want to check multiple accounts you would have to do that one at a time, or use "--dev-mode" when starting indexer to allow rewinding with the /v2/accounts search endpoint
