### ISSUE TITLE
Monitor for misbehaving queries

### ISSUE THREAD

**Issue by winder** [algorand/indexer#790]
## Problem

We have several ways to detect misbehaving queries:
1) 503 status codes, this should be set when a request times out.
2) 500 status codes, all other unexpected internal errors set this code.
3) Log warning: `Misbehaving handler did not exist after 1 second.` is written when a query is unable to terminate after a timeout.

There is a specific action to take for each of these:
1) 503 status codes indicate queries which should be included with #669 
2) 500 status codes may be a bug that could be fixed.
3) These suggest a context is not being used correctly. The issue is easy to fix, but hard to find. We've already tried to fix all contexts, but probably missed some, so monitoring is a great tool for finding any that were missed.

## Solution

A datadog dashboard would be great. Some sort of alert/notification sent to indexer developers would be even better.

**Comment by yaovi-a** [comment]
@winder We are logging these 503s and 500 status codes in datadog. Do you have access or need access? 

https://app.datadoghq.com/logs?query=%40proxy.name%3A%28mainnet-mainnet-node-8080%20OR%20mainnet-mainnet-indexer-reader-8980%29%20%20service%3Anginx-ingress-controller&cols=host%2Cservice%2C%40proxy.name&index=%2A&integration_id=&integration_short_name=&messageDisplay=inline&saved_view=111987&stream_sort=desc&viz=stream&from_ts=1640630213120&to_ts=1640631113120&live=true

**Comment by onetechnical** [comment]
This had more effect when we were running the mobile indexers. This is unlikely to catch anything of significance in our internal services cluster.
