### ISSUE TITLE
Address query with address-role=receiver param results in hour+ queries

### ISSUE THREAD

**Issue by purestaketdb** [algorand/indexer#791]
### Subject of the issue

User made queries include new `address-role=receiver` query parameter. Queries were at a low velocity. Each query resulted in a thread in the db exceeding 1hr in execution time and a 504 timeout for the user.  

DB query
"SELECT t.round, t.intra, t.txnbytes, t.extra, t.asset, h.realtime FROM txn t JOIN block_header h ON t.round = h.round JOIN txn_participation p ON t.round = p.round AND t.intra = p.intra WHERE p.addr = $1 AND (t.txn -> 'txn' ->> 'rcv' = $2 OR t.txn -> 'txn' ->> 'close' = $3 OR t.txn -> 'txn' ->> 'arcv' = $4 OR t.txn -> 'txn' ->> 'aclose' = $5) AND t.txid != '' ORDER BY p.addr, p.round DESC, p.intra DESC LIMIT 1000"

### Your environment

MainNet
Indexer 2.6.5
8 core CPU / 64gb RAM in a cluster  

### Steps to reproduce

1. Execute `/v2/transactions?address-role=receiver&address={address}` in MainNet
2. Monitor response and DB 

### Expected behaviour
Indexer responds with expected transaction response

OR 

If Indexer times out, kill the query

### Actual behaviour
Indexer times out on response, query lives on consuming sessions and CPU, repeated attempts crash server

**Comment by brianolson** [comment]
I'm curious about the `EXPLAIN` of that on a loaded db, and if we could rearrange the query to trick Postgres into doing the right thing. Maybe rearrange it to
```sql
WITH (SELECT p.addr, p.round, p.intra FROM txn_participation p WHERE p.addr = $1) AS ptxn
SELECT ... JOIN ptxn ON t.round = p.round AND p.intra = t.intra WHERE ...
```
I want Postgres to figure out that it can do a cheap filter on txns by txn_participation before doing the expensive filter digging into all the txn fields. (I suspect it isn't doing that, `EXPLAIN` may confirm/dispense that theory)

**Comment by algoanne** [comment]
This should now cause a query timeout, let us know if that's not the case. (of course, we know it might also be desirable to make this more performant, but that's a different concern)
