### ISSUE TITLE
Application Transaction Filters

### ISSUE THREAD

**Issue by barnjamin** [algorand/indexer#809]
## Problem

I'd like the ability to filter transactions by ApplicationArgs and application OnComplete.

This will be useful especially with application calls that conform to the ABI spec allowing a user to query for transactions that call the method 0xdeadbeef which maps indirectly to something like  "add(uint64,uint64)uint64"

It may only be necessary to allow filtering on the first argument since it specifies the method called

## Urgency

Not urgent

**Comment by algoanne** [comment]
will keep this in our backlog, but note that we probably won't work on this kind of additional feature in the near future.
