### ISSUE TITLE
What is Dev Mode?

### ISSUE THREAD

**Issue by Blackglade** [algorand/indexer#819]
## Problem

The dev mode option is available on the Algorand Indexer, but I am able to only find little information regarding this flag. The only mention of it is in the docs is to turn on an api that allows you to search for the historical balance of an account at a particular block, but this query doesn't seem to work at all. 

https://developer.algorand.org/docs/get-details/indexer/#historical-data-searches

Would love some more information as to the purpose of this mode.

**Comment by winder** [comment]
The "account at round" feature is very expensive, so by default it's limited to the `/v2/accounts/<addr>` endpoint.

dev-mode allows you to search for many accounts at a particular round with the `/v2/accounts` endpoint.

I think that's the only place we actually used dev-mode. Maybe we should turn this into an undocumented internal feature, it probably isn't useful for most people deploying Indexer.

**Comment by Blackglade** [comment]
Gotcha! Is this mode working properly? I tried the example listed in the docs and it doesn't seem to work. I can only get data about the latest round. I've ensured the `--dev-mode` is working correctly.

**Comment by winder** [comment]
> Gotcha! Is this mode working properly? I tried the example listed in the docs and it doesn't seem to work. I can only get data about the latest round. I've ensured the `--dev-mode` flag is enabled.

Sorry I missed your response until now. What command are you using? It should be something like `/v2/accounts/<addr>?round=18000000`. This query could take a while depending on which round you request.

**Comment by algoanne** [comment]
Closing this since the question was answered. If you need further help getting this to work, feel free to use Discord to reach out.
