### ISSUE TITLE
Reserve DB Connection Handles for Block Import

### ISSUE THREAD

**Issue by winder** [algorand/indexer#827]
## Problem

It is currently possible for queries to compete with the block import process. If queries exhaust the database connections it can cause the import process to fall behind.

## Solution

Reserve DB connections for the import process.

Tolik has told me that block import currently requires two connections. This would require some amount of refactoring in the way we use pgx.

## Dependencies

Configurable connection pool size: #826

**Comment by gmalouf** [comment]
With release of Conduit, this issue no longer makes sense for the indexer.
