### ISSUE TITLE
Design: explore scaling options using postgres

### ISSUE THREAD

**Issue by algoanne** [algorand/indexer#849]
**Context**
indexer as it is currently designed will one day face the following bottleneck: Postgres tables have a maximum size of 32TB. Currently, the size of indexer (which is mostly the transactions table) is 1TB, but this amount is likely to grow exponentially with the ecosystem. 

**What are you looking for?**
a first approach we want to explore is to scale indexer while sticking with a Postgres DB. 

The output of this story should be a design document for the Postgres-based scaling solution outlining the architecture and suggesting the work steps to achieve it.

**Comment by kirse** [comment]
2nd-ing this.  It is already getting hard to find providers with enough NVMe drive space + IOPS to both store and serve this data reliably.  You can squeeze out 4TB at most of the well-known Cloud providers, but that is usually at the cost of ditching RAID.  Further, many block storage options - esp. ones that are SSD backed - are too slow and the Indexer chokes.

This is a rapidly accelerating issue that some folks in the community are working to solve at great cost to their experiments (not cheap *at all* to spec out these high capacity nodes), but Algorand really needs to start putting some engineering oomph behind this sooner than later.

**Comment by urtho** [comment]
My own experiments show that switching indexer storage engine to CockroachDB allows for x3 reduction in space requirements thanks to efficient columnar compression. Not a "stick to Postgres" solution though - just a benchmark.

**Comment by urtho** [comment]
https://sql.algonode.cloud (a public service) runs with 2.8.2 indexer on PG14 with txn table partitioned by round. The range split is manual to fit 10mln TXN per partition. This solves 32TB limit, does not seem to have any negative impact but cannot tell for sure until there are some standardized indexer workloads/benchmarks :D :D
