### ISSUE TITLE
Performance Enhancement txn_participation missing Primary Key

### ISSUE THREAD

**Issue by juls858** [algorand/indexer#860]
## Problem

FiveTran sync tool is unable to properly replicate the txn_participation table because it lacks a primary key. Every other table has a PK defined. 

Query to show primary keys.
```sql
SELECT
  table_schema,
  table_name,
  (table_schema, table_name) IN (
     SELECT
        _schema.nspname AS table_schema,
        _table.relname  AS table_name
     FROM pg_catalog.pg_constraint c
        LEFT JOIN pg_catalog.pg_class _table ON c.conrelid = _table.oid
        LEFT JOIN pg_catalog.pg_namespace _schema ON _table.relnamespace = _schema.oid
     WHERE c.contype = 'p'
  ) AS has_primary_key
FROM information_schema.tables
WHERE table_type = 'BASE TABLE' AND table_schema NOT IN ('information_schema', 'looker_scratch') AND
     NOT table_schema ~ '^pg_';
```

## Solution

Please add a primary key to txn_participation table.

**Comment by brianolson** [comment]
The only index on `txn_participation` is set up in
https://github.com/algorand/indexer/blob/develop/idb/postgres/internal/schema/setup_postgres.sql#L33-L40
on `( addr, round DESC, intra DESC )`
When I was initially developing this I think PostgreSQL didn't support a PRIMARY KEY with a descending column, but if that's not correct then we could fix this.

**Comment by juls858** [comment]
It's possible to have both a primary key and a unique key. Many tools use the primary key to infer relationship semantics.

**Comment by brianolson** [comment]
```sql
CREATE TABLE IF NOT EXISTS txn_participation (
addr bytea NOT NULL,
round bigint NOT NULL,
intra smallint NOT NULL,
PRIMARY KEY ( addr, round DESC, intra DESC )
);
ERROR:  syntax error at or near "DESC"
LINE 5: PRIMARY KEY ( addr, round DESC, intra DESC )
```
It's a waste of space to have indexes that aren't needed. You could add `PRIMARY KEY (addr,round,intra)` to your `txn_participation` declaration, but I wouldn't recommend it generally.

**Comment by algoanne** [comment]
Thanks for the suggestion! As per Brian's comments above, you're welcome to make changes to your own instance but we won't do this for the general indexer.
