### ISSUE TITLE
Inconsistent behavior of endpoint

### ISSUE THREAD

**Issue by purestaketdb** [algorand/indexer#905]
### Subject of the issue

The applications/{application-id}/logs endpoint introduced in 2.8 will return results even when the application is deleted. However applications/{application-id} will not.

### Your environment

Testing against Betanet using appId 732250114

### Steps to reproduce

1. GET v2/applications/732250114 (betanet)
2. GET v2/applications/732250114/logs

### Expected behaviour

Both return 

```
{
    "message": "no application found for application-id: 732250114"
}
```

### Actual behaviour

Without /logs, get expected results, with /logs get 

```
{
    "application-id": 732250114,
    "current-round": 16548691,
    "log-data": [
        {
            "logs": [
                "AAAAAAAAAQA="
            ],
            "txid": "QJM3UR6IWSLFYJGUGKVX6DUEJLHKVDXKL4MKHRGAIE3S33BKSGIQ"
        }
    ],
    "next-token": "_PH6AAAAAAArAAAA"
}
```

This is minor - but inconsistent

**Comment by winder** [comment]
@algoanne could you investigate this, I don't know if it is intended behavior or a bug.

**Comment by algochoi** [comment]
I think this is intended behavior. The logs are associated with a particular transaction (and its corresponding txid) rather than the application itself (Indexer also queries the transaction table for the logs rather than the application table). The endpoint naming, however, is a bit misleading.
