### ISSUE TITLE
Asset transfer amount from indexer does not match explorer amount. 

### ISSUE THREAD

**Issue by gskapka** [algorand/indexer#918]
### Subject of the issue

Asset transfer amount in explorer different to amount in block when pulled from the indexer.

### Steps to reproduce

```
curl https://algoindexer.algoexplorerapi.io/v2/blocks/19560833 | jq '.transactions[84]."asset-transfer-transaction".amount'
> 18446744073709552000
```

vs what's shown for the same tx on the explorer here:

https://algoexplorer.io/tx/6NCNZDDQTJBRTIEBRL6FYJXVGP5XFV2RQRKCBZENH3YDXBYI7Y4Q

```
Amount: 18,446,744,073,709.551615 AF-STAKE
```

I see that the amount on the explorer is `u64::MAX`, with a decimal in there, yet what's in the block from the indexer is > `u64::MAX` because it appears to have been rounded up.

What's the actual greatest amount allowed in the algo protocol?

**Comment by algoanne** [comment]
Hi @gskapka, this is not an indexer issue, but probably a Randlabs issue (the group maintaining both Algoexplorer and the algoexplorer API) - you should reach out to them!
