### ISSUE TITLE
Validator doesn't appear to read from stdin

### ISSUE THREAD

**Issue by onetechnical** [algorand/indexer#926]
### Subject of the issue

New validator revisions appear to have broken reading from stdin.

```
head -5 betanet_accounts.txt | ./algorand-indexer util validator \
  --algod-token $(cat $ALGOD_DATA/algod.token) \
  --algod-url $(cat $ALGOD_DATA/algod.net) \
  --indexer-token $(cat $ALGOD_DATA/algod.token) \
  --indexer-url localhost:8980
```

Contents of betanet account:

```
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
AA0vep3WoUF8PriIbYqssNVCohZpIR+9d+pVbtzuZIY=
ABEjkaCdVIbNZDOVIvADeRCog1Enj+4Zv9EaSBZ6IAc=
ABGyNJrr+5O46xxG+zFyax+sBT1aZ9kSwexIEQP9eIU=
ABOLDzXb0DV8D2W1bOyClBVuyUxgjVAAawnp38BMbrc=
```

This does work if you pass each individual address with the `--addr` flag.

### Your environment

algod: 3.5.0.beta [rel/beta] (commit #13d95bff)
indexer: 2.10.0-rc1 compiled at 2022-03-10T19:54:39+0000 from git hash d83723113ea0ee555076b96bdf97675741646615
OS: Ubuntu 20.04
EC2 Instance: i3.8xlarge
DB: Postgres 13

### Steps to reproduce

1. Run the above command, observe checking 0 entries (0/0)

### Expected behaviour

The above should return 5 checked entries.

### Actual behaviour

Returns checked 0/0.

**Comment by winder** [comment]
Resolved by #926
