### ISSUE TITLE
Indexer APIs with callWithTimeout have ctx race that leads to forced postgres connection close

### ISSUE THREAD

**Issue by urtho** [algorand/indexer#952]
Noticed that my indexers are creating and destroying postgres connections at the rate of almost 50% of the request rate.
Indexer behaves like there was no connection pooling.  Wireshark confirmed that properly acked ROLLBACK command still causes pgxpool to terminate the connection.

Added a this little diagnostic tweak:

```go
go func() {
        db.yieldAccountsThread(req)
        close(req.out)
        if rerr := tx.Rollback(ctx); rerr != nil {
            db.log.Printf("rollback error: %s", rerr)
        }
    }()
```

And my logs are now full of:

`{"level":"info","msg":"rollback error: timeout: context canceled","time":"2022-04-06T22:21:15Z"}`

This means that the CTX got cancelled before the rollback was confirmed and according to the pgx source this forces connection close. 

This seems harmless but also totally negates the gains from having a connection pool. 

And the reason seems to be a race between 
`close(req.out)` and `tx.Rollback(ctx)` 

`close(req.out)` causes  `defer cancel()` on the ctx in `callWithTimeout` to fire (nondeterministically) ahead of actual rollback .

Doing the tx.Rollback before the close(req.out) should solve the problem at a cost of a slight delay to the API response. Or rollback might be called with a new, unrealated, deadline ctx. 

This is on 2.10.0 , linux 64bit . Not able to reproduce in the lab! But happens to all productions servers.

**Comment by urtho** [comment]
It seems that other places in the code employ both solutions. 
Either tx.Rollback(ctx) followed by close or connection cleanup with background context.

**Comment by urtho** [comment]
Also some places seem to lack the call to tx.rollback altogether. 

```go
	go func() {
		db.yieldApplicationsThread(rows, out)
		close(out)
	}()
```

```go
	go func() {
		db.yieldAppLocalStateThread(rows, out)
		close(out)
	}()
```

**Comment by urtho** [comment]
Running a patch on testnet in production 😈  with tx.rollback before close. 
PG connection pooling now behaves as expected. Wireshark confirms no TCP setups/teardown once the pool stabilizes. 

Attached is the my debugging diff :
[txrollback.patch.txt](https://github.com/algorand/indexer/files/8442094/txrollback.patch.txt)

**Comment by urtho** [comment]
Forking is not healthy for CPU. Once postgres no longer had fork to accept 200 connections per sec this happened:
avg 15m CPU usage dropped from 80% to 16% :)

![2022-04-07_20h32_42](https://user-images.githubusercontent.com/176747/162272752-38cc71b3-3436-46a9-8302-255534d13442.png)

**Comment by winder** [comment]
@urtho thanks for the detailed report. We have the fix ready for the next release.
