### ISSUE TITLE
indexer 2.11.0 release

### ISSUE THREAD

**Issue by onetechnical** [algorand/indexer#976]

**Comment by algobarb** [comment]
From Will: Two major things:
1) I'm hoping to get this into the release. We can create the release branch but please hold off on tagging / creating binaries this week. https://github.com/algorand/indexer/issues/973
2) We need to make sure everyone signs off on the release notes. There is a default configuration change that all indexer runners need to consider, so it's important that we pro-actively communicate that and make sure the messaging is clear.

**Comment by algobarb** [comment]
Gary: we need to communicate out to indexer runners several days before release goes out.

**Comment by algobarb** [comment]
Running into errors with the pipeline because of the new git update:
```
git submodule update --init && cd third_party/go-algorand && \
	make crypto/libs/`scripts/ostype.sh`/`scripts/archtype.sh`/lib/libsodium.a
fatal: unsafe repository ('/go/src/github.com/algorand/indexer' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /go/src/github.com/algorand/indexer
make: *** [go-algorand] Error 128
Makefile:24: recipe for target 'go-algorand'
```

**Comment by algobarb** [comment]
Created a cluster: all-internal-yellow-2022-04-29-v2-10-0

**Comment by algobarb** [comment]
Found validation bug with 404 errors. Bug has been fixed in https://github.com/algorand/indexer/pull/987

Validation script works. Now rebuilding `2.11.0-rc2`

**Comment by algobarb** [comment]
`2.11.0` built and signed. Waiting to move to releases folder tomorrow. Github Release Draft has been created.
